### ISSUE TITLE
Lock Status Not Updating - Always Stuck on "Locked" (v2.36.6, EU, Kia EV3)

### ISSUE THREAD

**Issue by Petch91** [Hyundai-Kia-Connect/kia_uvo#1084]
Region and Brand of car
Region: EU (Belgium)
Brand: Kia
Model: Kia EV3

Version of the integration
v2.36.6

Describe the bug
The integration does not update the lock status of my vehicle. It always remains "locked", even when I unlock the car using the official Kia Connect app or manually.

Debug logs if an error occurred
I will provide debug logs if necessary.

To Reproduce

Lock the car using the Kia Connect app or the car's key.

Check the status in Home Assistant → It shows "locked" (which is correct).

Unlock the car using the Kia Connect app or the key.

Check the status in Home Assistant → It still shows "locked", even though the car is actually unlocked.

Expected behavior
The lock status should update in Home Assistant when the car is unlocked, instead of staying stuck on "locked".

Screenshots

![Image](https://github.com/user-attachments/assets/5b18019b-870d-4871-85a3-6c39dbf273e0)

Additional context
This issue occurs even after restarting Home Assistant and reloading the integration.

Thanks a lot for your work on this integration and for your future help! 🙌

**Comment by cdnninja** [comment]
Have you left the car unlocked for a full scan interval?

**Comment by Petch91** [comment]
Yes, I left my car unlocked for more than an hour, but the status in Home Assistant still shows “locked”. The issue persists even after multiple scan intervals.

**Comment by cdnninja** [comment]
Did the last updated reflect a time it was unlocked?  If cloud isn't aware it won't show.

**Comment by cdnninja** [comment]
Debug logs would be good as well.

**Comment by Petch91** [comment]
Yes, I double-checked and the last update time was during the period the car was unlocked. The status still showed "locked"

![Image](https://github.com/user-attachments/assets/f5fe7d1c-185b-40af-a2f0-a66b7377f7cc)

![Image](https://github.com/user-attachments/assets/84c16ca8-97b3-4b4d-8e5c-e5ea2eb2b8dd)

[logKia.log](https://github.com/user-attachments/files/19732488/logKia.log)

**Comment by cdnninja** [comment]
Should be fixed in next release. If you want to test it out update from master branch or edit your manifest file to switch the API to 3.35.5.

**Comment by Petch91** [comment]
Hi,
After updating the manifest.json and switching to API version 3.35.6, I noticed that the status finally changed to "unlocked", which is great!

However, it still does not update back to "locked" when the car is actually locked again. The status remains stuck on "unlocked".

Let me know if you need new debug logs for this behavior. Thanks again for your help and great work on the integration! 🙏

**Comment by cdnninja** [comment]
Could you try 3.35.8 for me?   If it doesn't work could you check if inverted?

**Comment by rutj87** [comment]
@cdnninja have tested latest updates and lock status still isn't updating.
Have forced update and still no change. Checked in Kia app and confirmed it's showing correctly.

**Comment by cdnninja** [comment]
To confirm you edited your manifest file?

**Comment by rutj87** [comment]
Confirmed and even tired w .9

Stuck in unlocked status now. Confirmed that isn’t inverted (not changing
regardless of either locked or unlocked status) and have forced update to
ensure pushing details back.

**Comment by rutj87** [comment]
Are you pulling the door locked status from the attribute within the data sensor?

**Comment by cdnninja** [comment]
Data sensor is just a dump from the API to put it all in one spot.  Logs will match it.  

This is what is being done: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/706008972e07ecb5cbcd6fc3993a9c3a40b6c02a/hyundai_kia_connect_api/ApiImplType1.py#L203-L229

Vehicle.is_locked is then displayed in the interface in kia_uvo here: https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/4541ca15402db3cade37c1b72cc8ea183ae322b8/custom_components/kia_uvo/lock.py#L51-L53

These cars don't report overall locked but rather each door.

**Comment by rutj87** [comment]
@cdnninja - I think this one is wrong...

            bool(get_child_value(state, "Cabin.Door.Row1.Driver.Open"))
            if get_child_value(state, "Cabin.Door.Row1.Driver.Open") is not None

It should be "Cabin.Door.Row1.Driver.Lock"

there is no reference to open in the data attribitues and the other three doors are "Lock"

Returns 0 when locked and 1 when unlocked.

**Comment by rutj87** [comment]
Correct, 0 is locked and 1 is unlocked

**Comment by cdnninja** [comment]
Okay 3.35.11 may work.

**Comment by rutj87** [comment]
Quick initial check - looks like it is working!

Team effort :)

**Comment by rutj87** [comment]
@cdnninja - looks like it only worked once which is strange. 
Will see if i can look at when I check out V2L in more detail.

**Comment by Petch91** [comment]
Hi,
Just tested with the latest version and API 3.35.11, and everything works perfectly now! 🔒🔓
Lock status updates correctly in both directions.

Thanks a lot for the fix and your awesome work on this integration! 🙏🚗
