### ISSUE TITLE
After 2.40 plugin won't start

### ISSUE THREAD

**Issue by alicornea** [Hyundai-Kia-Connect/kia_uvo#1119]
**Version of the integration**
2.40
**Describe the bug**
After update to new version plug in won't start and I get the following message.
Car userd: 2024 Hyundai Sante Fe, Europe

**Debug logs if an error occurred**
Failed setup, will retry: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 128, in _async_update_data await self.hass.async_add_executor_job( ...<2 lines>... ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in check_and_force_update_vehicles self.check_and_force_update_vehicle(force_refresh_interval, vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 132, in check_and_force_update_vehicle self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 98, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 235, in update_vehicle_with_cached_state self._update_vehicle_properties_ccs2(vehicle, state) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/ApiImplType1.py", line 449, in _update_vehicle_properties_ccs2 elif vehicle._ev_estimated_current_charge_duration > 0: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: '>' not supported between instances of 'NoneType' and 'int' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 137, in _async_update_data await self.hass.async_add_executor_job( self.vehicle_manager.update_all_vehicles_with_cached_state ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 93, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 98, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 235, in update_vehicle_with_cached_state self._update_vehicle_properties_ccs2(vehicle, state) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/ApiImplType1.py", line 449, in _update_vehicle_properties_ccs2 elif vehicle._ev_estimated_current_charge_duration > 0: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by michaelmog88** [comment]
Same. Works fine if I downgrade to v2.39.1

**Comment by DennisIsanders** [comment]
Yup!! Same here!!.

**Comment by cdnninja** [comment]
Fixed, sorry about that.

**Comment by joeredhead76** [comment]
Same here. Error message reads: Failed setup, will retry: Config Not Ready: Expecting value: line 1 column 1 (char 0)

**Comment by PrivatePilotGuy** [comment]
> Fixed, sorry about that.

Installled today’s update just and still have the same issue as others unfortunately.   Appreciate your work with the plugin, but just a heads up.  🤙

**Comment by PrivatePilotGuy** [comment]
![Image](https://github.com/user-attachments/assets/ed020cd0-bc2b-4980-800b-1674d2057b1d)

Just fyi

**Comment by joeredhead76** [comment]
I downgraded to version 2.39.1 as others did:
Click on the integration card in HACS.
Click on the three dots icon top right of the page.
Select Redownload.
Choose the version you want from the dropdown list.
Click Download.

**Comment by PrivatePilotGuy** [comment]
> I downgraded to version 2.39.1 as others did: Click on the integration card in HACS. Click on the three dots icon top right of the page. Select Redownload. Choose the version you want from the dropdown list. Click Download.

Just did exactly that, and unfortunately it’s still broken for me, even after a full reboot of HA.  I think something may be borked in the configuration now perhaps but I’m not quite sure how to address such.

**Comment by cdnninja** [comment]
I doubt config.  Nothing changed with that.   

Would need debug logs to see.  The initial error should be solved in the latest code. Could be something else.

**Comment by joeredhead76** [comment]
Downgrading does not work... deleted my post to avoid confusion.

**Comment by DennisIsanders** [comment]
It did in my case.Op 1 mei 2025 om 20:04 heeft joeredhead76 ***@***.***> het volgende geschreven:﻿
joeredhead76 left a comment (Hyundai-Kia-Connect/kia_uvo#1119)
Downgrading does not work... deleted my post to avoid confusion.

**Comment by kharder69** [comment]
Downgrading to 2.39.1 works.

**Comment by cdnninja** [comment]
Reminding again on the latest need debug logs.

**Comment by saue0** [comment]
2025-05-01 13:33:45.321 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> mybluelink.ca</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">939106957e5ca288</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">70.55.123.41</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>


    </div>
  </div>

  <script>
  window._cf_translation = {};
  
  
</script>

<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'939106957e5ca288',t:'MTc0NjEyMDgyNS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>

2025-05-01 13:33:45.322 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.153 seconds (success: False)

**Comment by saue0** [comment]
The problem seem to be with the login. I deleted the entity and can not readd it anymore

```
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
intégration: Hyundai / Kia Connect (documentation, problèmes)
S'est produit pour la première fois: 15:16:18 (2 occurrences)
Dernier enregistrement: 15:16:57

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 119, in login
    response = response.json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kharder69** [comment]
> Disable and try again tomorrow.   It was probably left on the other code for a bit so kept retrying until IP blocked.  

As soon as I replace custom_components/kia_evo with version 2.39.1 it works immediately after restart of home assistant.

**Comment by PrivatePilotGuy** [comment]
> Disable and try again tomorrow. It was probably left on the other code for a bit so kept retrying until IP blocked.

I am headed home now and will unplug my modem and cycle things to get it to draw a new IP and will report back. I went back to the latest version 

> As soon as I replace custom_components/kia_evo with version 2.39.1 it works immediately after restart of home assistant.

Seems to work for some, not for all – there’s at least two of us now who have tried that without success.

**Comment by bverkron** [comment]
Downgrading to 2.39.1 did not work for me either. I had first tried upgrading to 2.40.1 and then to 2.39.1.

Has anyone done a complete uninstall / re-install? I tried that for a different issue in the past and it did not work due to it being a login issue so don't want to bother with all that hassle if someone else tried and it didn't work.

**Comment by cdnninja** [comment]
I highly doubt reinstall will work.  If your getting the above policy deny message you just need to wait.  Trying more will extend your ip restriction.

**Comment by PrivatePilotGuy** [comment]
Grabbing a new IP didn’t help at all.   So I’ve just disabled the integration for the time being.   How long do you anticipate it’ll need to be disabled for before it’s safe to reenable it successfully?

**Comment by GraemeDBlue** [comment]
I noticed since the integration stopped working as above, it also blocked my form the BlueLink app itself, in fact it completely kicked me out the app  and only started working this morning and had to log back in

**Comment by xKronyx** [comment]
Same problem here, updated to 2.40 yesterday, go back to 2.39. Today i tried 2.40.1 and still have the problem, go back to 2.39


[2 appareils](http://10.1.1.9:8123/config/devices/dashboard?historyBack=1&config_entry=557bcee8dc2da6a08f4bb85c5df6ef88) et [74 entités](http://10.1.1.9:8123/config/entities?historyBack=1&config_entry=557bcee8dc2da6a08f4bb85c5df6ef88)
Échec de la configuration, nouvel essai: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json return complexjson.loads(self.text, **kwargs) ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads return _default_decoder.decode(s) ~~~~~~~~~~~~~~~~~~~~~~~^^^ File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386,

**Comment by cdnninja** [comment]
I would try 24 hours after.  Only once though say from the native app before turning the integration on. 

I wonder if we can change the retry interval home assistant itself uses to help prevent that in the future.

**Comment by PrivatePilotGuy** [comment]
> I would try 24 hours after. Only once though say from the native app before turning the integration on.
> 
> I wonder if we can change the retry interval home assistant itself uses to help prevent that in the future.


I’d prefer to not lengthen the polling interview too much - I log some data from Bluelink plus my wife uses the SOC display on my dashboard quite often to see what her range is, etc - having that info get more than an hour or so stale wouldn’t be ideal personally for us at least.  

It was a bug in the last release that led to this happening to begin with I presume?  It had been running perfectly for me for many weeks before that so I’m assuming it was only the issue that led to the block, not necessarily the polling interval necessarily?

**Comment by cdnninja** [comment]
Home assistant has an auto retry if failed update.  That's OOTB functionality.   

The code failed to parse some data caused by a bug. Home assistant would retry setup over and over until blocked. 

I'm referencing extending that retry for failure, not the update interval.

**Comment by PrivatePilotGuy** [comment]
> I'm referencing extending that retry for failure, not the update interval.

Gotcha, sounds like a good move.  👍

**Comment by contactpjb** [comment]
Hi All - I'm seeing the following with 2.40.1:

```
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 10 column 1 (char 9)

```
The integration appears to be hammering the server repeatedly so I have disabled it for now.

Was 2.40.1 supposed to address the issues referred to earlier in this thread (which resulted in the IP blocks)? Is downgrading to 2.39.1 advised?

Thanks!

**Comment by xKronyx** [comment]
I did go back to 2.39 (Previous version) and it work after the reboot. I'm waiting 24h to try again to see if it will solve the problem.

**Comment by cdnninja** [comment]
> Hi All - I'm seeing the following with 2.40.1:
> 
> ```
>   File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
>            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
> simplejson.errors.JSONDecodeError: Expecting value: line 10 column 1 (char 9)
> ```
> 
> The integration appears to be hammering the server repeatedly so I have disabled it for now.
> 
> Was 2.40.1 supposed to address the issues referred to earlier in this thread (which resulted in the IP blocks)? Is downgrading to 2.39.1 advised?
> 
> Thanks!

With just the snippet I can't tell if that is a login error or not.  If so I would expect 2.40.1 to be okay after disabling to let it clear. 

I haven't seen anyone provide the initial error on 2.40.1 so I am assuming that is resolved.  Those that have said downgrading works haven't confirmed for me what happens on 2.40.1.

**Comment by fongd** [comment]
My integration had been working fine but recently started failing. I tried to troubleshoot the issue which culminated in me removing the integration and trying to set it back up again. However, no matter what I do now, I can't even login to Bluelink anymore. All I get now is an "Unexpected error" message at login. I've waited over 24 hours since my configuration attempt in case this is due to rate limiting. I'm running 2.40.1.

If it matters, I'm logging into Bluelink for Hyundai Canada. Here are the relevant logs for my latest login attempt:

```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: May 2, 2025 at 02:38:53 (3 occurrences)
Last logged: 01:17:06

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 119, in login
    response = response.json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by alicornea** [comment]
After update to 2.41 I still get an error:
Failed setup, will retry: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 128, in _async_update_data await self.hass.async_add_executor_job( ...<2 lines>... ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in check_and_force_update_vehicles self.check_and_force_update_vehicle(force_refresh_interval, vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 132, in check_and_force_update_vehicle self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 98, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 235, in update_vehicle_with_cached_state self._update_vehicle_properties_ccs2(vehicle, state) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/ApiImplType1.py", line 449, in _update_vehicle_properties_ccs2 elif vehicle._ev_estimated_current_charge_duration > 0: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: '>' not supported between instances of 'NoneType' and 'int' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 137, in _async_update_data await self.hass.async_add_executor_job( self.vehicle_manager.update_all_vehicles_with_cached_state ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 93, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 98, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 235, in update_vehicle_with_cached_state self._update_vehicle_properties_ccs2(vehicle, state) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/ApiImplType1.py", line 449, in _update_vehicle_properties_ccs2 elif vehicle._ev_estimated_current_charge_duration > 0: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by cdnninja** [comment]
Thank you for that - mistake in my fix.   2.40.2 is out.

**Comment by GraemeDBlue** [comment]
> Thank you for that - mistake in my fix.   2.40.2 is out. 

Thanks,  seems to be working again

**Comment by xKronyx** [comment]
Yep working for me ! it solve the problem 

Thanks !

**Comment by PrivatePilotGuy** [comment]
![Image](https://github.com/user-attachments/assets/034f85ec-08b4-4681-aa4e-9cc06bd41241)

No joy here.  

I had everything disabled for about 36 hours, tried very briefly with 2.40.1 earlier this morning also without success, just updated to 2.40.2, and still get the above.

**Comment by xKronyx** [comment]
Try to uninstall, reboot, install 2.40.2

**Comment by PrivatePilotGuy** [comment]
> Try to uninstall, reboot, install 2.40.2, reboot

Somebody earlier in this thread reported trying that and then being completely unable to even reinstall again IIRC, or unable to login or something.   @cdnninja your thoughts on this approach?

**Comment by xKronyx** [comment]
> > Try to uninstall, reboot, install 2.40.2, reboot
> 
> Somebody earlier in this thread reported trying that and then being completely unable to even reinstall again IIRC, or unable to login or something. [@cdnninja](https://github.com/cdnninja) your thoughts on this approach?

That's what i did this morning and it worked for me, it was just trying to help you ...

**Comment by PrivatePilotGuy** [comment]
> > > Try to uninstall, reboot, install 2.40.2, reboot
> > 
> > 
> > Somebody earlier in this thread reported trying that and then being completely unable to even reinstall again IIRC, or unable to login or something. [@cdnninja](https://github.com/cdnninja) your thoughts on this approach?
> 
> That's what i did this morning and it worked for me, it was just trying to help you ...

I certainly appreciate the help, don’t get me wrong, I’m just a little bit paranoid about getting into a situation where everything goes pear shaped on my HA install as I’m the poster boy for Murphys Law lol.

**Comment by cdnninja** [comment]
Uninstall would be no different than upgrading and rebooting for this issue.   You for sure what latest code.  If that code doesn't work check in the detailed log if cloud flare blocking.  If so turning the integration off and waiting longer is key.

**Comment by PrivatePilotGuy** [comment]
Just checked the debug log and indeed it seems like cloudflare is still the culprit here.   Damn, I hope this clears eventually as I am guessing there’s no way for end users like us to have any effect whatsoever so far as contacting anyone who could address it.  

I do have a Cloudflare account and thought that maybe logging in from my home IP address might somehow help things so far as whitelisting the IP, however I can report back that that didn’t help at all.

Does anybody have any insight on how cloudflare blocks like this? It doesn’t seem to be IP based as I have tried a new IP, presumably it’s not account based if it’s not even getting past Cloudflare, so would it be MAC address based?

**Comment by PrivatePilotGuy** [comment]
VPN made no difference, so I’m guessing Cloudflare is blocking based on MAC address.    Unfortunately not easy to change in a HAOS situation.

**Comment by bverkron** [comment]
I have done a complete uninstall, reboot, reinstall cycle and stills can’t get it working. I attempted to enable debug logging via this…

… but I just get this in the log, nothing about Cloudflare

```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 11:50:42 AM (1 occurrences)
Last logged: 11:50:42 AM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 119, in login
    response = response.json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by cdnninja** [comment]
Leave it disabled.   Try only briefly.  Wait awhile between trying.  The more it's left running most likely the longer the block will last.

**Comment by cdnninja** [comment]
> I have done a complete uninstall, reboot, reinstall cycle and stills can’t get it working. I attempted to enable debug logging via this…
> (on mobile right now so just I commented a previous debug config)
> 
> ![Image](https://github.com/user-attachments/assets/47f515b3-2d86-43eb-b8cd-1aed30512667)
> 
> … but I just get this in the log, nothing about Cloudflare
> 
> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.kia_uvo.config_flow
> Source: custom_components/kia_uvo/config_flow.py:148
> integration: Hyundai / Kia Connect (documentation, issues)
> First occurred: 11:50:42 AM (1 occurrences)
> Last logged: 11:50:42 AM
> 
> Unexpected exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 974, in json
>     return complexjson.loads(self.text, **kwargs)
>            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
>     return _default_decoder.decode(s)
>            ~~~~~~~~~~~~~~~~~~~~~~~^^^
>   File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
>     obj, end = self.raw_decode(s)
>                ~~~~~~~~~~~~~~~^^^
>   File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
>            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
>     await validate_input(self.hass, user_input)
>   File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
>     token: Token = await hass.async_add_executor_job(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 119, in login
>     response = response.json()
>   File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 978, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> ```
> 
> 

That isn't the logs. That's a crash dump error.  Full logs would show more.

**Comment by alicornea** [comment]
all good. it works now with 2.40.2.
thank you for your effort and prompt investigation

**Comment by PrivatePilotGuy** [comment]
> I am also still unable to login via the integration but there is at least one other issue that is tracking a similar (same?) problem, this one for Canada specifically: [#1124](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1124)

@cdnninja, is it possible that the other issue quoted is actually the root of the problem here, not necessarily what we assumed it was so far as what's causing the block?   

I am a Canadian Bluelink user as well which this seems isolated to if I'm reading things correctly?

**Comment by joeredhead76** [comment]
I cannot even set it up anymore. I removed it completed, tried adding it, and I get "Unexpected error" when I enter my credentials. And I know username / password / PIN are corrected since I tested them on Bluelink website and my phone.

**Comment by novamcgurk** [comment]
Same here, for EU

**Comment by PrivatePilotGuy** [comment]
^and this is why I never tried the uninstall and reinstall option.   Although I’m still no bueno so far as getting it working again unfortunately.

**Comment by cdnninja** [comment]
> I cannot even set it up anymore. I removed it completed, tried adding it, and I get "Unexpected error" when I enter my credentials. And I know username / password / PIN are corrected since I tested them on Bluelink website and my phone.

That would be expected based on the cloudflare error.  Make sure this is left disabled for the time being.

**Comment by bverkron** [comment]
Is there a way to confirm if the cloud flare error is the issue during a fresh setup? I also had removed and re-added it entirely when troubleshooting earlier. Left it for somewhere around 48 hours between attempts and still get `Unexpected error`. Is there a curl or wget or something we can try from the HA server to emulate it and confirm the actual response?

**Comment by cdnninja** [comment]
You could use the python API library or other tools yes.    Either or.

**Comment by cdnninja** [comment]
We found a fix for the error on the Canadian side, could try it for EU. Could someone confirm the issue still exists?

**Comment by bverkron** [comment]
I'm in Canada and it worked.

Just did the typical update, reboot HA, add integration, login. Took longer to login / initialize than usual but it worked!

Thank you!!!

**Comment by cdnninja** [comment]
@bverkron  this is the EU thread - different code so hoping to hear from the EU folks to see if I need to replicate the fix to EU or if it resolved.

**Comment by joeredhead76** [comment]
It's working now!
