### ISSUE TITLE
Unexpected error login

### ISSUE THREAD

**Issue by lsmllc** [Hyundai-Kia-Connect/kia_uvo#1163]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Canada Hyundai
**Version of the integration**
2.41.2
**Describe the bug**
All entities lost connection, unable to login anymore

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

Not sure how I can see logs if the integration is not active
**To Reproduce**
If all entities from this integration do not work, log off and try to log in back to have the error.
**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/66dee9d9-c25a-4f0f-9441-5bd8273abcf2)
**Additional context**

**Comment by lsmllc** [comment]
I tried with version 2.42.1 same prob

**Comment by franquosino** [comment]
There we go again.  Same problem here. The Hyundai server in Canada has been everything but trouble. Fortunately, this community has been amazing and find a way to make it work again. I'll post the log shortly.

**Comment by PrivatePilotGuy** [comment]
Ditto here, all offline as well.

**Comment by franquosino** [comment]
Hoping this log may help the brilliant minds with this issue!

2025-06-19 15:14:35.978 DEBUG (SyncWorker_10) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> mybluelink.ca</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9526615a48a7051c</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">99.199.112.199</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>


    </div>
  </div>

  <script>
  window._cf_translation = {};
  
  
</script>

<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'9526615a48a7051c',t:'MTc1MDM3MTI3NS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>

2025-06-19 15:14:35.979 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.132 seconds (success: False)

**Comment by cdnninja** [comment]
Looks like cloudscraper 3.X was released last week. It may help. It however isn't on pypi so can't be used just yet.

**Comment by Latulippe9** [comment]
Same problem here

**Comment by franquosino** [comment]
I should add that I can login the web https://www.mybluelink.ca/ page and the App without a problem.

**Comment by devzwf** [comment]
I think it is a reoccurence of the previous issue 
just me thinking hi..... at least same symptoms on my side

**Comment by mouset96** [comment]
Why is there always problem with Canada Bluelink. Just randomly stops working.

**Comment by PrivatePilotGuy** [comment]
> Looks like cloudscraper 3.X was released last week. It may help. It however isn't on pypi so can't be used just yet.

So for the masses, where does this put us so far as getting things working again?

And as Mouset96 mentioned, why do you think it’s only the Canadian Bluelink service that these issues are repeatedly happening with?  Some overzealous network admin here with an axe to grind over HA, or just bad luck with their network infrastructure here?

**Comment by cdnninja** [comment]
Waiting for that new version to get released and trying it out.  

Open to others to try other solutions. 

As for why - hard to know if intentional or not.

**Comment by JordanM1738** [comment]
I've done some tests on my end. When I run locally
`bluelink --region Canada --brand Hyundai --username FOO --password BAR --pin 1234 -v info --json infos.json`
The script crashes as if reading the cache isn't working.
If I force a refresh of the data from mybluelink.ca and run the script immediately afterward, it works, and I get the vehicle information in Python.
But then the bluelink site tells me information is unavailable, as if the cache has disappeared. So the script becomes nonfunctional again. I have to force a refresh again from the bluelink site.

HA side
Unfortunately, nothing works from Home Assistant without Cloudscraper 3.
Regardless of the headers, there's always the message "Why have I been blocked?"
I tested with Cloudscraper 3.
In Home Assistant, the integration still doesn't work because the API doesn't return everything as before, but it respond.

I ran the following in Python in Home Assistant:
`bluelink --region Canada --brand Hyundai --username FOO --password BAR --pin 1234 -v info --json infos.json`
It works with Cloudscaper 3. I added in setup.py
```
install_requires=[
    requirements,
    'cloudscraper @ git+https://github.com/VeNoMouS/cloudscraper.git',
],
```
I'm no longer stuck at login, but some endpoints return an error 7999.
```
DEBUG:urllib3.connectionpool:https://mybluelink.ca:443 "POST /tods/api/ntcmsgcnt HTTP/1.1" 200 None
DEBUG:hyundai_kia_connect_api.KiaUvoApiCA:hyundai_kia_connect_api - Test Token Response {"error":{"errorCode":"7999","errorDesc":"We apologize, but your request could not be processed. Please try again. later."},"responseHeader":{"responseCode":1,"responseDesc":"Failure"}}
```

In the end, we have all the data retrieved by the Python script running on the HA machine.

Here's my test branch if it helps, as I won't be able to make any progress in the coming days.
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/compare/master...JordanM1738:hyundai_kia_connect_api:cloudscraper3

Inspired by https://github.com/andyfase/egmp-bluelink-scriptable/blob/main/src/lib/bluelink-regions/canada.ts for the headers

**Comment by mgguinne** [comment]
Hi,

Same issue as last time. Fixed by doing a password reset in the Kia app. 

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1060#issuecomment-2744970781

**Comment by PrivatePilotGuy** [comment]
> Hi,
> 
> Same issue as last time. Fixed by doing a password reset in the Kia app.
> 
> [#1060 (comment)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1060#issuecomment-2744970781)


Just to clarify, it fixed things for you this time around as well, ie it’s working again for you again currently with just a Pw reset?

**Comment by PrivatePilotGuy** [comment]
So, I changed my password for Bluelink in order to test this theory, however now for the life of me I can’t figure out how to update it in the integration.  Can somebody point me in the right direction please.

**Comment by dr1rrb** [comment]
> So, I changed my password for Bluelink in order to test this theory, however now for the life of me I can’t figure out how to update it in the integration.  Can somebody point me in the right direction please. 

You have to remove the integration and then add it back.

**Comment by PrivatePilotGuy** [comment]
So, can confirm this doesn’t work unfortunately- it won’t even let me log in again at all now.

**Comment by joeredhead76** [comment]
I am getting the same error message. I tried resetting the password, but did not work. Note that I can access Bluelink via website. I am in Canada with Hyundai car.

**Comment by mgguinne** [comment]
Yes. Worked for me. My integration had stopped working. Adding a new hub
with same user name and password failed. Reset my password. Removed current
hub in integration, add new one and works now.

**Comment by JordanM1738** [comment]
> Yes. Worked for me. My integration had stopped working. Adding a new hub
> with same user name and password failed. Reset my password. Removed current
> hub in integration, add new one and works now.
> […](#)

Thanks for the tip, but unfortunately Bluelink is different in every country, this thread is for Canada. So it works differently and here we can confirm that Cloudflare is the problem at least for the connection but i think they changed some endpoints too 😔.
Maybe add Canada tag on this thread?

**Comment by PrivatePilotGuy** [comment]
> Yes. Worked for me. My integration had stopped working. Adding a new hub
> with same user name and password failed. Reset my password. Removed current
> hub in integration, add new one and works now.
> […](#)


Not Canada I presume?

This current issue is strictly Canadian service specific as Jordan mentioned.

**Comment by jbilodea** [comment]
Same problem here, I'm in Canada too for Hyundai. It is working on Android, web and Hubitat.

**Comment by franquosino** [comment]
What a relief to see the update for this app this morning, but to no avail :(

There was a mention earlier about waiting for a new release. I'm not sure if that was about a new release of this app or Cloudscraper/Cloudfare. 

The use of this app as reminder to charge which EV in the garage at night is so convenient and is sure missed right now. It feels like we had more knowledgeable people involved in tackling the same issue not that long ago. I wish I could contribute in a more meaningful manner!

**Comment by PrivatePilotGuy** [comment]
@cdnninja, perhaps I’m just not understanding things clearly, but there’s another Bluelink based script that I use on my iPhone (both in widget and scripting) that is indeed still working just fine on our Bluelink Canada service.  I use it for auto-locking the doors on our i5 when we walk away, as well as providing a neat widget with basic display info.  

![Image](https://github.com/user-attachments/assets/dd01d095-82ac-4225-b685-baa371581d6b)

Any idea why it’s still working but Kia Uvo isn’t?

Here’s a link to that project on GitHub as well for reference.  

https://github.com/andyfase/egmp-bluelink-scriptable

**Comment by jparchib** [comment]
Hi, where are we on this issue? I have the same problème here in Canada and was following this thread silently but I’m surprised to see no new post since for days.

**Comment by KingMat666** [comment]
> Hi, where are we on this issue? I have the same problème here in Canada and was following this thread silently but I’m surprised to see no new post since for days.

I tried latest version and still have same problem, i'm thinking about deleting this addon, cannot trust it anymore.

I tried deleting it and adding it back, i can't even log back in, i'm getting the unexpected error message.

**Comment by jparchib** [comment]
> > Hi, where are we on this issue? I have the same problème here in Canada and was following this thread silently but I’m surprised to see no new post since for days.
> 
> I tried latest version and still have same problem, i'm thinking about deleting this addon, cannot trust it anymore.
> 
> I tried deleting it and adding it back, i can't even log back in, i'm getting the unexpected error message.

Yeah, but what are the options? Is there any other integrations that works?

**Comment by JordanM1738** [comment]
as written in my previous comment [here](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-2993919809). on my side it works since I published my merge request. The problem here is that we have to wait for an external library to publish its update and we are blocked by that. in my merge request, I add it manually and it works. so the minute the external library publishes its version, we will be unblocked
This is the dependency: https://github.com/VeNoMouS/cloudscraper/issues/289#issuecomment-3010678934

**Comment by JordanM1738** [comment]
> > Hi, where are we on this issue? I have the same problème here in Canada and was following this thread silently but I’m surprised to see no new post since for days.
> 
> I tried latest version and still have same problem, i'm thinking about deleting this addon, cannot trust it anymore.
> 
> I tried deleting it and adding it back, i can't even log back in, i'm getting the unexpected error message.

We’re all regular people with varying levels of experience in development. We’re doing our best to maintain this project, even though Hyundai is currently making frequent updates to their APIs and systems, which we heavily depend on.

If you’re experiencing issues, you’re definitely not alone — we’re all affected. And, we’re working hard to find solutions as quickly as possible.

If you’re able to contribute, your help is more than welcome to move things forward faster. And if you find any workarounds or alternatives, please share them with the community.

That’s the spirit of Home Assistant — a community where we help each other and move forward together!

If you read the release notes when you update the addon, the latest updates do not affect Canada.

**Comment by KingMat666** [comment]
> > > Hi, where are we on this issue? I have the same problème here in Canada and was following this thread silently but I’m surprised to see no new post since for days.
> > 
> > 
> > I tried latest version and still have same problem, i'm thinking about deleting this addon, cannot trust it anymore.
> > I tried deleting it and adding it back, i can't even log back in, i'm getting the unexpected error message.
> 
> We’re all regular people with varying levels of experience in development. We’re doing our best to maintain this project, even though Hyundai is currently making frequent updates to their APIs and systems, which we heavily depend on.
> 
> If you’re experiencing issues, you’re definitely not alone — we’re all affected. And, we’re working hard to find solutions as quickly as possible.
> 
> If you’re able to contribute, your help is more than welcome to move things forward faster. And if you find any workarounds or alternatives, please share them with the community.
> 
> That’s the spirit of Home Assistant — a community where we help each other and move forward together!
> 
> If you read the release notes when you update the addon, the latest updates do not affect Canada.

I'm just an end user and know nothing about all that happens in the background...

**Comment by jbilodea** [comment]
I've modified the app in Hubitat many months ago for it to work in Canada.  And I never changed it since then, but it still work in Hubitat.  Since I also use Home assistant as a second hub (but I know nothing about the coding stuff in Home Assistant), I don't understand why it does not work in HA but it still work in Hubitat without any change.

**Comment by PrivatePilotGuy** [comment]
I’m still genuinely curious why the other plug-in that I mentioned above that provides my desktop widget and script still works but this one doesn’t.

By no means am I trying to be negative about this specific plug-in, it’s all way over my head and I genuinely appreciate everything that the developers do (and have done) to keep it operational especially considering they are all volunteers, but I am trying to understand things better and I thought perhaps throwing that other script into the discussion may provide some useful tidbits on perhaps figuring out why they’re still able to successfully access the API whereas kia_uvo is being blocked. 🙂

**Comment by cdnninja** [comment]
Give the latest a go.  

As for reason, Cloudflare is a product that can try detect and stop this.  So hard to say.

**Comment by PrivatePilotGuy** [comment]
> Give the latest a go.

Was there a new release?  I’m not seeing it.  

Thanks again for all your work.   You guys maintaining this need to have a “Buy Me A Coffee” button somewhere so all the rest of us can contribute towards your time.

**Comment by cdnninja** [comment]
Looks like can't publish to pypi with a GitHub dependency so that won't work for mass deploy.  

May need to wait for those working on cloud scraper.

**Comment by PrivatePilotGuy** [comment]
Is there a manual install option?  I’m willing to learn and get my fingers dirty lol.

**Comment by jbilodea** [comment]
> Is there a manual install option? I’m willing to learn and get my fingers dirty lol.

Me too, I coded in Hubitat and if I could learn something in HA I would be happy to help.

**Comment by jlogo99** [comment]
> Give the latest a go.
> 
> As for reason, Cloudflare is a product that can try detect and stop this. So hard to say.

What is "the latest"? Where do I find it?  I'm in Canada and still having the issues with HA not being able to use the integration.  This has thrown off multiple automations I have setup, so I'm really interested in doing whatever is necessary to get this working again.  Thanks!!

**Comment by jlogo99** [comment]
Hi, hoping for some insight here.  I'm in Canada and still have this login issue receiving "Unexpected Error". As of July 3rd I have all the latest versions installed and still have problems.
Log file attached (ignore the other ISY and other various minor errors in the log)

[home-assistant_kia_uvo_2025-07-04T02-03-10.042Z.log](https://github.com/user-attachments/files/21049316/home-assistant_kia_uvo_2025-07-04T02-03-10.042Z.log)

Really hoping to get this working again, as I have several automations dependent on it.  Any assistance would be much appreciated.

**Comment by sircharlo** [comment]
Mine randomly started working... Seems to be intermittent.

**Comment by jlogo99** [comment]
Mine is consistently not working. Still getting the Unexpected error when
trying to log in

**Comment by PrivatePilotGuy** [comment]
> Mine randomly started working... Seems to be intermittent.


Canada?

**Comment by PrivatePilotGuy** [comment]
> Mine is consistently not working. Still getting the Unexpected error when
> trying to log in
> […](#)


Just tried again for the first time in a week or so, same.

**Comment by jlogo99** [comment]
Yes. From Canada.

**Comment by PrivatePilotGuy** [comment]
> Yes. From Canada.
> […](#)


Very interesting that it’s kinda sorta operational again as is.  Anything particularly different about your set up that you think might be at the root of this?

**Comment by jlogo99** [comment]
> > Yes. From Canada.
> > […](#)
> 
> Very interesting that it’s kinda sorta operational again as is. Anything particularly different about your set up that you think might be at the root of this?

It might be kinda sort operational for others but not me.  @sircharlo indicated he was operational again, but not sure if he's in Canada.

My overall HA installation is pretty basic. Many integrations all through HACS, no custom tinkering of coding per se on my part.  At the Kia/Hyundai integration was plan vanilla was was working perfectly until a few weeks ago when it just stopped.  

If you scroll back a few posts in this thread, I've uploaded my error log when trying to sign on (or "add a hub" as the case may be with the integration).

**Comment by adamgreenberg07** [comment]
I'm in Canada and mine has not worked for the past couple of weeks. I've been trying to get it set up on a daily basis and it has not worked.

This is the log info from the last time I tried to get it working in case it is of any help to anyone working on the problem


This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 2:54:18 PM (2 occurrences)
Last logged: 11:17:33 PM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 976, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 119, in login
    response = response.json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 980, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jlogo99** [comment]
Hi, is any other information required to help resolve this issue for users in Canada?

**Comment by sircharlo** [comment]
> Hi, is any other information required to help resolve this issue for users in Canada?

Hi there @jlogo99,

Just a quick note to mention that the developer of this add-on is generously contributing their time and work for free. Comments asking for updates—while well-meaning—don’t help speed up issue resolution and can create unnecessary noise in the thread.

If you're eager to help move things forward, I’d encourage you to try investigating the root cause of the issue, share any technical findings you uncover, or even submit a pull request if you're able. Otherwise, it might be best to hold off on additional comments unless there’s new and relevant information to add.

**Comment by JordanM1738** [comment]
For those who are currently blocked and want to get things working again, I’ve published the following comment 2 weeks ago https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-2993919809

This branch includes all the necessary adjustments (correct headers, etc.) to make the integration work, even though cloudscraper 3 hasn't been officially released yet. We are dependent on an external library and cannot publish an update without it https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-3016950791

✅ This setup has been working without interruptions for me since June 21st (Hyundai only — I don’t have other brands to test).
⚠️ Please note: This is a manual workaround and assumes you’re comfortable modifying custom components.

https://github.com/JordanM1738/hyundai_kia_connect_api/tree/cloudscraper3
Place the downloaded folder inside your Home Assistant /config/ directory.

Edit manifest.json:
Open the file located at:
/config/custom_components/kia_uvo/manifest.json
Replace the requirements line with:

"requirements": ["./hyundai_kia_connect_api"]
Restart Home Assistant

**Comment by jlogo99** [comment]
> > Hi, is any other information required to help resolve this issue for users in Canada?
> 
> Hi there [@jlogo99](https://github.com/jlogo99),
> 
> Just a quick note to mention that the developer of this add-on is generously contributing their time and work for free. Comments asking for updates—while well-meaning—don’t help speed up issue resolution and can create unnecessary noise in the thread.
> 
> If you're eager to help move things forward, I’d encourage you to try investigating the root cause of the issue, share any technical findings you uncover, or even submit a pull request if you're able. Otherwise, it might be best to hold off on additional comments unless there’s new and relevant information to add.

Thank you for your comments.  I do appreciate that developer is spending their personal time and energy supporting this - which is precisely why I asked if I could provide any other information to help in their efforts.  

My ability to debug coding issues is limited.  I can contribute however but offering to work to recreate the situation, provide any other debug info etc. assuming that the developer does not live in Canada and may not be able to reproduce region specific issues.

**Comment by mouset96** [comment]
> For those who are currently blocked and want to get things working again, I’ve published the following comment 2 weeks ago [#1163 (comment)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-2993919809)
> 
> This branch includes all the necessary adjustments (correct headers, etc.) to make the integration work, even though cloudscraper 3 hasn't been officially released yet. We are dependent on an external library and cannot publish an update without it [#1163 (comment)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-3016950791)
> 
> ✅ This setup has been working without interruptions for me since June 21st (Hyundai only — I don’t have other brands to test). ⚠️ Please note: This is a manual workaround and assumes you’re comfortable modifying custom components.
> 
> https://github.com/JordanM1738/hyundai_kia_connect_api/tree/cloudscraper3 Place the downloaded folder inside your Home Assistant /config/ directory.
> 
> Edit manifest.json: Open the file located at: /config/custom_components/kia_uvo/manifest.json Replace the requirements line with:
> 
> "requirements": ["./hyundai_kia_connect_api"] Restart Home Assistant

Thanks, working again for me after this.

**Comment by franquosino** [comment]
I understand that this section is not a tutorial and please pardon my ignorance. I'm simply quite eager to get things working again.

I can manage to modify the manifest.json file as per the instructions, but not sure where to  exactly place the downloaded https://github.com/JordanM1738/hyundai_kia_connect_api/tree/cloudscraper3  folder in the /config/ directory. Is it under /config/custom_components/kia_uvo or in a different folder under /config/custom_components?

Any pointer would be greatly appreciated. Thank you.

**Comment by mouset96** [comment]
> I understand that this section is not a tutorial and please pardon my ignorance. I'm simply quite eager to get things working again.
> 
> I can manage to modify the manifest.json file as per the instructions, but not sure where to exactly place the downloaded https://github.com/JordanM1738/hyundai_kia_connect_api/tree/cloudscraper3 folder in the /config/ directory. Is it under /config/custom_components/kia_uvo or in a different folder under /config/custom_components?
> 
> Any pointer would be greatly appreciated. Thank you.

From the addon store download "Samba share". After downloading go to configuration tab and input a username and password and then start the addon. Go to logs and there should be an IP address near the bottom. Copy and paste it into file explorer with \\\ before (eg. \\\192.168.0.123) and enter your username + password. You should see the config folder and then follow the rest of Jordan's instructions.

Also make sure the folder is named "hyundai_kia_connect_api". Had to rename it from hyundai_kia_connect_api-cloudscraper3.

**Comment by lsmllc** [comment]
Hi all, 

The issue is now resolved — everything is working perfectly using the branch from @JordanM1738. Huge thanks to everyone involved for your efforts, it's truly incredible. I’ve learned a lot through this process and really appreciate the support!

@cdnninja Do you want me to close this ticket, or will you handle it once you have time to implement Cloudscraper 3 (since it's not officially released yet)?

**Comment by jlogo99** [comment]
> Hi all,
> 
> The issue is now resolved — everything is working perfectly using the branch from [@JordanM1738](https://github.com/JordanM1738). Huge thanks to everyone involved for your efforts, it's truly incredible. I’ve learned a lot through this process and really appreciate the support!
> 
> [@cdnninja](https://github.com/cdnninja) Do you want me to close this ticket, or will you handle it once you have time to implement Cloudscraper 3 (since it's not officially released yet)?

Hi @lsmllc - are you in Canada?  I've tried the above process from JordanM1738 and still not working for me. Same Unexpected Error message.

**Comment by lsmllc** [comment]
> > Hi all,
> > The issue is now resolved — everything is working perfectly using the branch from [@JordanM1738](https://github.com/JordanM1738). Huge thanks to everyone involved for your efforts, it's truly incredible. I’ve learned a lot through this process and really appreciate the support!
> > [@cdnninja](https://github.com/cdnninja) Do you want me to close this ticket, or will you handle it once you have time to implement Cloudscraper 3 (since it's not officially released yet)?
> 
> Hi [@lsmllc](https://github.com/lsmllc) - are you in Canada? I've tried the above process from JordanM1738 and still not working for me. Same Unexpected Error message.

Did you change the name of the folder to hyundai_kia_connect_api ? This is what I was missing earlier.

**Comment by jlogo99** [comment]
Yes.  I made that change.

**Comment by lsmllc** [comment]
You could install vscode addon and screenshot your HA folder and compare it to mine
https://community.home-assistant.io/t/home-assistant-community-add-on-visual-studio-code/107863?u=frenck

<img width="1036" height="1089" alt="Image" src="https://github.com/user-attachments/assets/a856c60f-83f6-4c22-a5e5-963738be4bb7" />

**Comment by jlogo99** [comment]
The error I get in the logs is:
Setup failed for custom integration 'kia_uvo': Requirements for kia_uvo not
found: ['./hyundai_kia_connect_api'].

The only way I can resolve the error is by removing the ./ from the
pathname.  When I do that, the integration loads fine, and I assume it's
pointing to the newly downloaded directory for the requirements, but when I
try to sign on (ie. add a hub) , I get the ongoing unexpected error
message.

**Comment by Edzilla2000** [comment]
Please everyone, you're spamming everyone that follows this issue.
If you need help, make a post on the home assistant community forums and put the link in here once.

**Comment by logname** [comment]
Please see https://community.home-assistant.io/t/kia-uvo-integration/297927/333?u=smarthomeprimer
Hope this helps. Don't reply here.

**Comment by BardaktakiAdam** [comment]
Same problem

**Comment by franquosino** [comment]
Unless I'm mistaken, the solution proposed by JordanM1738 with Cloudflare last month appears to be no longer working.  I got the same result with a downgraded version (V2.42.3). Back to the original identified unexpected authentication error.

**Comment by dr1rrb** [comment]
> Unless I'm mistaken, the solution proposed by JordanM1738 with Cloudflare last month appears to be no longer working. I got the same result with a downgraded version (V2.42.3). Back to the original identified unexpected authentication error.

Same on my side, no longer working since this morning 😭, but with a slightly different error message this time:

```
[hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response {"error":{"errorCode":"7404","errorDesc":"The login information you entered is incorrect. Multiple incorrect login attempts may result in account lock-out."},"responseHeader":{"responseCode":1,"responseDesc":"Failure"}}
```

(And I didn't changed my password!)

Tried to disable the integration for few hours to see if it could be a temporary lock-out.

**Comment by JordanM1738** [comment]
Since yesterday they added a deviceid field to add to the header when calling the login API. So they have strengthened security. I really think they are trying to block Home Assistant.
Without device id we have this error.


> > Unless I'm mistaken, the solution proposed by JordanM1738 with Cloudflare last month appears to be no longer working. I got the same result with a downgraded version (V2.42.3). Back to the original identified unexpected authentication error.
> 
> Same on my side, no longer working since this morning 😭, but with a slightly different error message this time:
> 
> ```
> [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response {"error":{"errorCode":"7404","errorDesc":"The login information you entered is incorrect. Multiple incorrect login attempts may result in account lock-out."},"responseHeader":{"responseCode":1,"responseDesc":"Failure"}}
> ```
> 
> (And I didn't changed my password!)
> 
> Tried to disable the integration for few hours to see if it could be a temporary lock-out.

**Comment by dr1rrb** [comment]
> Since yesterday they added a deviceid field to add to the header when calling the login API. So they have strengthened security. I really think they are trying to block Home Assistant. Without device id we have this error.
> 

Humm good to know 👍 Looking at the content of this device id from browser, it seems to be the `user-agent+OS+<number>+<number>` encoded in base64. Wondering what are those number and if we can just put random stuff here, did you tried yet ?

**Comment by dr1rrb** [comment]
Ok was able to restore the integration by hard-coding the `DeviceId` header in the  `KiaUvoApiCA.py` file on line 120:

<img width="1353" height="615" alt="Image" src="https://github.com/user-attachments/assets/13c4940a-96eb-447c-be5f-9d32b9e1087e" />

(Requires restart of HA)

No sure how long it will last ...

**Comment by JordanM1738** [comment]
Yes, when I add my Android App ID, it works fine, but I haven't tried other solutions yet, like a random ID. Maybe I can test in the next few days, right now I just made sure to reproduce the App payload so that it works.

**Comment by dr1rrb** [comment]
Tried with some random numbers, and got it to load in HA. Opened a PR on your repo https://github.com/JordanM1738/hyundai_kia_connect_api/pull/2 :)

FYI Put a generic header:

`TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0`

which is 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0+Win32+1234+1234`

**Comment by franquosino** [comment]
Just tried to put the generic header:

TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0

and got:

This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 11:19:52 AM (1 occurrence)
Last logged: 11:19:52 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/hyundai_kia_connect_api/KiaUvoApiCA.py", line 120, in login
    headers["Deviceid"] = TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0' is not defined

**Comment by gboudreau** [comment]
> Unexpected exception Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user await validate_input(self.hass, user_input) File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input token: Token = await hass.async_add_executor_job( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/hyundai_kia_connect_api/KiaUvoApiCA.py", line 120, in login headers["Deviceid"] = TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NameError: name 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0' is not defined

You're simply missing quotes : `headers["Deviceid"] = "..."`

**Comment by franquosino** [comment]
> > Unexpected exception Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user await validate_input(self.hass, user_input) File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input token: Token = await hass.async_add_executor_job( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/config/hyundai_kia_connect_api/KiaUvoApiCA.py", line 120, in login headers["Deviceid"] = TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ NameError: name 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzOC4wLjAuMCBTYWZhcmkvNTM3LjM2IEVkZy8xMzguMC4wLjArV2luMzIrMTIzNCsxMjM0' is not defined
> 
> You're simply missing quotes : `headers["Deviceid"] = "..."`

Oops! Thank you. Yes, it works now! Hope it lasts another week...

**Comment by cdnninja** [comment]
Please open a pull request to the api library for this and I will merge it

**Comment by jbilodea** [comment]
> Please open a pull request to the api library for this and I will merge it

Tested it and worked fine for now, thank you.

**Comment by simplisticton** [comment]
Problem persists with 2.42.5

**Comment by jbilodea** [comment]
> Problem persists with 2.42.5

I removed the integration, redownloaded, rebooted and reinstalled and it works for me.

**Comment by Latulippe9** [comment]
I tried to remove and reinstall it and it didn't work for me.

Le dim. 20 juill. 2025, 13 h 25, jbilodea ***@***.***> a
écrit :

**Comment by simplisticton** [comment]
> I removed the integration, redownloaded, rebooted and reinstalled and it works for me.

Unfortunately not for me -- did a complete remove & reinstall (with reboots), and it's still the same error as before.

**Comment by jbilodea** [comment]
not working anymore this morning :-(

**Comment by PrivatePilotGuy** [comment]
> not working anymore this morning :-(


I just installed the DeviceID Line 120 fix literally an hour ago, rebooted, and am back running again, so chances are your issue is something else.

**Comment by jbilodea** [comment]
> so chances are your issue is something else.

Just after the home assistant core update it stopped working, removed it and re-added it and still not working. :-(

**Comment by jkuffner** [comment]
> > so chances are your issue is something else.
> 
> Just after the home assistant core update it stopped working, removed it and re-added it and still not working. :-(

I'm having the same issue now.  Is anyone able to give some advice on how to apply the deviceid fix?  I'm not much of a developer to know.  I've tried redownloading the integration but that didn't fix anything.

**Comment by franquosino** [comment]
I just did the last Core update and this app stopped working again. It looks like Cloudflare blocked it again. Here is the log:


2025-07-22 11:50:11.178 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.145 seconds (success: False)
2025-07-22 11:50:13.895 WARNING (MainThread) [homeassistant.components.go2rtc.server] 11:50:13.895 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:81 > error="write tcp 127.0.0.1:11984->127.0.0.1:36304: write: broken pipe"
2025-07-22 11:50:16.659 DEBUG (SyncWorker_20) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> mybluelink.ca</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">96351f6d688b48f3</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">99.199.112.72</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>


    </div>
  </div>

  <script>
  window._cf_translation = {};
  
  
</script>

<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'96351f6d688b48f3',t:'MTc1MzIxMDIxNi4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"96351f6d688b48f3","serverTiming":{"name":{"cfExtPri":true,"cfEdge":true,"cfOrigin":true,"cfL4":true,"cfSpeedBrain":true,"cfCacheStatus":true}},"version":"2025.7.0","token":"6c9d26bdc06b45b582c9a7f72d0acd15"}' crossorigin="anonymous"></script>
</body>
</html>

2025-07-22 11:50:16.659 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.158 seconds (success: False)

**Comment by franquosino** [comment]
Follow up: I just restore HA core to yesterday, when everything was working fine, and this app connection remained unsuccessful. The current issue is likely unrelated to the HA core update.

**Comment by sircharlo** [comment]
1. Delete the integration's configuration from Settings > Devices & services.
2. Run this from wherever Home Assistant is running (a docker container, in my case):

```
pip uninstall cloudscraper
pip uninstall hyundai_kia_connect_api
pip install git+https://github.com/JordanM1738/hyundai_kia_connect_api.git@cloudscraper3
```

3. Add the integration from Settings.

This has been my workaround. It works consistently, and can be repeated whenever @JordanM1738 updates his branch.

**Comment by arim215** [comment]
> Follow up: I just restore HA core to yesterday, when everything was working fine, and this app connection remained unsuccessful. The current issue is likely unrelated to the HA core update.

Same Here... I tried resetting my Password, tried @JordanM1738 's fix, tried downgrading HA Core to 2025.7.2... but still not working

**Comment by jbilodea** [comment]
> pip uninstall cloudscraper
> pip uninstall hyundai_kia_connect_api
> pip install git+https://github.com/JordanM1738/hyundai_kia_connect_api.git@cloudscraper3

In a web terminal addon i tried the uninstall but it says cloudscrapper is not install  so i ONLY did
pip install git+https://github.com/JordanM1738/hyundai_kia_connect_api.git@cloudscraper3
I rebooted and now it works !

**Comment by cdnninja** [comment]
I would think running this once would also resolve this without installing other branches: 

`pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0`

I also wonder if we could add the git repo to the manifest.json file of the integration.  That way I could update it on the repo until cloudscraper publishes.

**Comment by cdnninja** [comment]
Could someone test this out after removing the manual fix? https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1203

**Comment by goalcam** [comment]
> Could someone test this out after removing the manual fix? [#1203](https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1203)

I'm getting an error in HA after making this change to the manifest. Syntax issue?

> Invalid requirement 'git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0'

The line in question in my manifest currently reads:
`  "requirements": [
    "hyundai_kia_connect_api==3.43.0",
    "git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0"
  ],`

**Comment by jkuffner** [comment]
> I would think running this once would also resolve this without installing other branches:
> 
> `pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0`
> 
> I also wonder if we could add the git repo to the manifest.json file of the integration. That way I could update it on the repo until cloudscraper publishes.

I ran the install and it's working fine for me now.

**Comment by arim215** [comment]
The new update (2.43.0) fixed it for me!

**Comment by Latulippe9** [comment]
Didn't work for me.

**Comment by jayscovill** [comment]
I also updated to 2.43.0 and it broke the integration.  Reverted back to 2.42.1 and that got it back working again.

**Comment by cdnninja** [comment]
> I also updated to 2.43.0 and it broke the integration.  Reverted back to 2.42.1 and that got it back working again.

Have you installed the cloud scraper version manually?

**Comment by jayscovill** [comment]
> > I also updated to 2.43.0 and it broke the integration.  Reverted back to 2.42.1 and that got it back working again.
> 
> Have you installed the cloud scraper version manually?

Have not tried that...on HASS Supervised so not entirely sure of the correct sequence.

**Comment by JB12134** [comment]
> Could someone test this out after removing the manual fix? [#1203](https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1203)

This worked for me when standard 2.43.0 did not. I never had the manual fix, I just stayed back a few versions before this broke. 
2023 Kia EV6 in Canada

**Comment by joeredhead76** [comment]
> > > I also updated to 2.43.0 and it broke the integration.  Reverted back to 2.42.1 and that got it back working again.
> > 
> > 
> > Have you installed the cloud scraper version manually?
> 
> Have not tried that...on HASS Supervised so not entirely sure of the correct sequence.

I am not a HASS expert, but I have the "Advanced SSH & Web Terminal" add-on. From Terminal, I typed:
pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0
and was able to install.

I ran these steps as indicated in above comment: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-3046593964

**Comment by jayscovill** [comment]
> > > > I also updated to 2.43.0 and it broke the integration.  Reverted back to 2.42.1 and that got it back working again.
> > > 
> > > 
> > > Have you installed the cloud scraper version manually?
> > 
> > 
> > Have not tried that...on HASS Supervised so not entirely sure of the correct sequence.
> 
> I am not a HASS expert, but I have the "Advanced SSH & Web Terminal" add-on. From Terminal, I typed: pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0 and was able to install.
> 
> I ran these steps as indicated in above comment: [#1163 (comment)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-3046593964)

Did you need to uninstall the integration first as mentioned above? or just update to latest version and run the pip install?

**Comment by joeredhead76** [comment]
> > > > > I also updated to 2.43.0 and it broke the integration.  Reverted back to 2.42.1 and that got it back working again.
> > > > 
> > > > 
> > > > Have you installed the cloud scraper version manually?
> > > 
> > > 
> > > Have not tried that...on HASS Supervised so not entirely sure of the correct sequence.
> > 
> > 
> > I am not a HASS expert, but I have the "Advanced SSH & Web Terminal" add-on. From Terminal, I typed: pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0 and was able to install.
> > I ran these steps as indicated in above comment: [#1163 (comment)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-3046593964)
> 
> Did you need to uninstall the integration first as mentioned above? or just update to latest version and run the pip install?

No, I did not need to uninstall the integration. I did receive an update no update to latest version this week (or last week), that I did, and then did the pip install.

**Comment by jayscovill** [comment]
> pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0

I updated to 2.43.0, ran `pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0
` in the SSH terminal, rebooted and the integration still would not load.

Reverted to 2.42.3 and it was able to load.

**Comment by cdnninja** [comment]
> > pip install git+[VeNoMouS/cloudscraper.git@3.0.0](https://github.com/VeNoMouS/cloudscraper.git@3.0.0)
> 
> I updated to 2.43.0, ran `pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0 ` in the SSH terminal, rebooted and the integration still would not load.
> 
> Reverted to 2.42.3 and it was able to load.

With 2.43.0 debug logs would be helpful.

**Comment by jeasimon** [comment]
> > > pip install git+[VeNoMouS/cloudscraper.git@3.0.0](https://github.com/VeNoMouS/cloudscraper.git@3.0.0)
> > 
> > 
> > I updated to 2.43.0, ran `pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0 ` in the SSH terminal, rebooted and the integration still would not load.
> > Reverted to 2.42.3 and it was able to load.
> 
> With 2.43.0 debug logs would be helpful.

Here is my own issue when I try v2.43.0: 

Enregistreur: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
intégration: Hyundai / Kia Connect (documentation, problèmes)
S’est produit pour la première fois: 11:32:35 (1 occurrence)
Dernier enregistrement: 11:32:35

Unexpected exception
Traceback (most recent call last):
File “/usr/local/lib/python3.13/site-packages/requests/models.py”, line 976, in json
return complexjson.loads(self.text, **kwargs)
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
File “/usr/local/lib/python3.13/site-packages/simplejson/init.py”, line 514, in loads
return _default_decoder.decode(s)
~~~~~~~~~~~~~~~~~~~~~~~^^^
File “/usr/local/lib/python3.13/site-packages/simplejson/decoder.py”, line 386, in decode
obj, end = self.raw_decode(s)
~~~~~~~~~~~~~~~^^^
File “/usr/local/lib/python3.13/site-packages/simplejson/decoder.py”, line 416, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/config/custom_components/kia_uvo/config_flow.py”, line 148, in async_step_user
await validate_input(self.hass, user_input)
File “/config/custom_components/kia_uvo/config_flow.py”, line 92, in validate_input
token: Token = await hass.async_add_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File “/usr/local/lib/python3.13/concurrent/futures/thread.py”, line 59, in run
result = self.fn(*self.args, **self.kwargs)
File “/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py”, line 120, in login
response = response.json()
File “/usr/local/lib/python3.13/site-packages/requests/models.py”, line 980, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jeasimon** [comment]
Version 2.42.3 as stated is working.

**Comment by robkowalchuk** [comment]
> Version 2.42.3 as stated is working.

Yep - same here once I reverted back to 2.42.3

**Comment by nodepoints** [comment]
> Version 2.42.3 as stated is working.

 I can confirm as well reverting to 2.42.3 works.

**Comment by cdnninja** [comment]
Debug logs are still needed.  Not just a stack trace.

**Comment by jeasimon** [comment]
> Debug logs are still needed. Not just a stack trace.

Right but I don’t want to risk update right now… so if someone have updated already and can share those debug log.

**Comment by jlogo99** [comment]
I removed the integration and downloaded 2.43.0 and rebooted.  No luck.  FYI - I am using this from Canada.
Attached is the debug log.

[home-assistant_kia_uvo_2025-07-26T13-20-37.907Z.log](https://github.com/user-attachments/files/21444742/home-assistant_kia_uvo_2025-07-26T13-20-37.907Z.log)

**Comment by cdnninja** [comment]
> I removed the integration and downloaded 2.43.0 and rebooted. No luck. FYI - I am using this from Canada. Attached is the debug log.
> 
> [home-assistant_kia_uvo_2025-07-26T13-20-37.907Z.log](https://github.com/user-attachments/files/21444742/home-assistant_kia_uvo_2025-07-26T13-20-37.907Z.log)

Is this with running the pip install of 3.0 of cloudscraper?

**Comment by jlogo99** [comment]
Yes.  It should be.  If there’s a way to confirm, let me know and I can
verify, but I did the pip install several days ago trying to get it to work.

**Comment by cdnninja** [comment]
pip show cloudscraper should say 3On Jul 26, 2025, at 3:41 PM, jlogo99 ***@***.***> wrote:﻿jlogo99 left a comment (Hyundai-Kia-Connect/kia_uvo#1163)
Yes.  It should be.  If there’s a way to confirm, let me know and I can

verify, but I did the pip install several days ago trying to get it to work.

**Comment by jlogo99** [comment]
Just ran pip show cloudscraper and it returned package not found.
Maybe I did an HA update at some point after installing?  Not sure.

I can re-install and re-test if that will help.  Let me know.

**Comment by cdnninja** [comment]
I noticed a fork of cloudscraper exists. I wonder if they had a falling out - I get the impression they did.     https://github.com/zinzied/cloudscraper

Anyone able to test?  Update to the latest release.  Then edit the manifest file to edit the Hyundai kia connect version to be 3.43.1.

**Comment by jlogo99** [comment]
[home-assistant_kia_uvo_2025-07-30T02-09-45.681Z.log](https://github.com/user-attachments/files/21499849/home-assistant_kia_uvo_2025-07-30T02-09-45.681Z.log)

I still can't get the integration to load, even with backleveling to 2.42.3.

So i upgraded to the latest 2.43.0 and also tried cloudscraper 3.1.0 from zinzied. Still no luck.  Debug info attached.

Any thoughts on how to get this working again?

**Comment by cdnninja** [comment]
No - someone will need to play with it to try figure out a way around. I can't replicate the issue.  I don't own a car anymore in CA.  When I run a login command with the API to an account without cars it works fine.

**Comment by JB12134** [comment]
My comment got buried, but I'm running the latest version and I manually put in the changes in this PR https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1203 . This worked fine for me. I'm not sure why it hasn't worked for others though.

**Comment by saue0** [comment]
As @JB12134 said, the PR https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1203 should work fine 

I did the `pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0` and it worked for me.
I will manually chage the Manifest for futhure restart of the container to take the change automaticaly.
Will pospone any new update for the moment    

PS. running 2.43.0

**Comment by cdnninja** [comment]
> As @JB12134 said, the PR https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1203 should work fine 
> 
> I did the `pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0` and it worked for me.
> I will manually chage the Manifest for futhure restart of the container to take the change automaticaly.
> Will pospone any new update for the moment    
> 
> PS. running 2.43.0

Maybe I merge that and see if works for everyone else.  I was confused with the intermittent results on it.

**Comment by jbilodea** [comment]
> I did the `pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0` and it worked for me.

I tried but still does not work. :-(

**Comment by cdnninja** [comment]
Your pip show result previously returned not installed.  That isn't possible.  As the integration won't even start without the older version of it. 

Where are you running this command from?

**Comment by arim215** [comment]
Maybe someone can help me here... dumb question probably, but when i open the terminal from the ssh add-on, i can't run the pip command... 

![image](https://github.com/user-attachments/assets/33f2ef55-7ec5-47fe-8420-11398fdd05ad)

**Comment by jbilodea** [comment]
> but when i open the terminal from the ssh add-on, i can't run the pip command...

I use the addon Advanced SSH & Web Terminal.

**Comment by jbilodea** [comment]
cdnninja: I know you don't have a Hyundai anymore.  I would be more than happy to help.  I have a Hyundai in Canada, I maintain the Hubitat version of this integration, I have Home assistant as a second hub, but I don't know home assistant coding too much.  But if I can help you I would be happy to help.

**Comment by jlogo99** [comment]
OK. I give up. 
I removed the integration.  Rebooted.
I did the pip install git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0 and had no errors.
I verifed with pip show cloudscraper and it confirmed it was installed.
I installed the integration (v2.43.0) through HACS. Rebooted
Now the integration won't even load, and I don't get any errors in the system logs.
I tried re-downloading 2.42.3 through HACS.  Rebooted
Same.  Integration won't load, and nothing in the system logs to show an error.

I'm definitely taking multiple steps backwards.  Now what??  Please HELP !!!

**Comment by jlogo99** [comment]
Same.  I have a Hyundai in Canada and more than willing to help with any
testing, traces, etc. assuming you can provide specific instructions.
My coding knowledge is not current to say the least.  Can you say COBOL?
lol. I'm dating myself now !!
Thanks !!

**Comment by cdnninja** [comment]
I can't provide specific instructions but in a nutshell here is a summary.  Debug logs show cloudflare is blocking our requests.   We don't know why but it is detecting this is abnormal traffic.   [cloudscraper](https://github.com/VeNoMouS/cloudscraper) is a package that helps get around this.  It hasn't been updated in awhile.   However they released a version 3.0 but didn't upload it to pypi. Pypi is how python gets all the packages it depends on.   They didn't upload because 3.0 they say is very broken, however people above seem to show it does work better than the old version we used.  Forcing it to install is the hard part. 

This is the library we use for this integration: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api 

If it works in theory the integration works.  Specially this file is the Canadian code: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/KiaUvoApiCA.py

Few comments on the above bit.   When you reboot home assistant it will install all requirements from the manifest file, and in turn requirements from the requirements requirements and so forth.    However it should be checking for greater than version.  For @arim215  it looks like core doesn't have pip installed, so I would edit the manifest.json file to match my potential fix here: https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1203 then reboot and see if it solves it - do that on the latest release first.  Pulling new kia_uvo releases will replace that file. 

If that consistently works for people we simple merge that PR.   However some reported above it didn't work so not comfortable rolling it to 1000s of users.   

Beyond that I don't have ideas but someone needs to tinker with that library to find a way to bypass cloudflare detection.  Something is picking up on these requests being us.

**Comment by jbilodea** [comment]
I just redownloaded the integration and tried this change by replacing in the manifest (and sure rebooted):

  "requirements": [
    "hyundai_kia_connect_api==3.43.0",
    "git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0"
  ],

And now it works !

**Comment by devzwf** [comment]
> I just redownloaded the integration and tried this change by replacing in the manifest (and sure rebooted):
> 
> "requirements": [ "hyundai_kia_connect_api==3.43.0", "git+https://github.com/VeNoMouS/cloudscraper.git@3.0.0" ],
> 
> And now it works !

Confirmed !!!!

**Comment by jlogo99** [comment]
Confirmed as well !! Works great now.

**Comment by cdnninja** [comment]
I have merged this PR and created a release so that should work for everyone for now.

**Comment by jeasimon** [comment]
I did not test the new PR but like everyone else, I updated, modified Manifest and restarted. Everything works fine.

**Comment by jbilodea** [comment]
> I have merged this PR and created a release so that should work for everyone for now.

I started from scratch: I removed the integration, redownloaded your new version, rebooted, readded it and now it works.  Thank you for your good work.

**Comment by arim215** [comment]
Can confirm the new 2.43.1 works! thank you

**Comment by emilio2003** [comment]
It still doesn't work for me. I redownloaded 2.43.1 and restarted HA. I'm on HA Core 2025.7.4, OS 16.0 hosted on a Proxmox Virtual Machine.

**Comment by alarobric** [comment]
Sat down tonight to try and take a look at this more closely only to find this thread and lots of great work going on. Updated and it's back working for me again as well!
