### ISSUE TITLE
"Last Updated at" is stating a future time.

### ISSUE THREAD

**Issue by rwelsh09** [Hyundai-Kia-Connect/kia_uvo#1316]
**Region and Brand of car**
Canada, Hyundai

**Version of the integration**
2.44.0

**Describe the bug**
See screenshot

**Screenshots**
<img width="983" height="135" alt="Image" src="https://github.com/user-attachments/assets/006599b3-21da-4052-a6e7-f18676275724" />

**Additional context**
I think this happened after a recent server maintenance.

**Comment by erikgeurts** [comment]
This is actually just the result of peculiar behavior of Home Assistant itself, often when something has happened a very short while ago (in the past), Home Assistant will display the "last changed" or "last updated" as "in 3 seconds" or "in 1 minute". This integration can't fix that.

**Comment by cdnninja** [comment]
We take the time from the server response and provide it to HA.   Could you check what the native app shows?

**Comment by rwelsh09** [comment]
Right now, the app is saying "Last updated 51 mins ago"  and HA is saying "In 3 hours" (it was 3:36 pm when I took the screenshots)

App:
<img width="574" height="238" alt="Image" src="https://github.com/user-attachments/assets/ec2318ac-9399-404a-9c69-e5e55c800e4f" />

HA more info screen:
<img width="794" height="209" alt="Image" src="https://github.com/user-attachments/assets/445fc445-088a-4037-911e-72ec9399493f" />

**Comment by cdnninja** [comment]
Probably a time zone issue.   Assuming home assistant time zone is set correctly please enable debug logs and provide them. Please also let me know the time zone.

**Comment by rwelsh09** [comment]
Timezone is GMT-07:00

To keep the log short I removed some information that I thought was irrelevant to this issue.
```
2025-09-23 08:43:18.947 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received forced vehicle data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20250923144317', '
2025-09-23 08:43:18.948 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Offset between vehicle and UTC: 0 hours
2025-09-23 08:43:18.948 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: 2025-09-23 14:16:26-06:00
2025-09-23 08:43:18.949 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2025-09-23 14:16:26-06:00
```

**Comment by cdnninja** [comment]
Some changes were just done on how time zones are read.  Could you retest?

**Comment by rwelsh09** [comment]
I used my Refresh Data automation and received this error.

```
Logger: homeassistant.components.automation.refresh_data
Source: helpers/script.py:524
integration: Automation (documentation, issues)
First occurred: 8:55:37 AM (1 occurrence)
Last logged: 8:55:37 AM

Refresh Data: Error executing script. Unexpected error for call_service at pos 2: can't subtract offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 524, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1012, in _async_step_call_service
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2799, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2842, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/services.py", line 68, in async_handle_force_update
    await coordinator.async_force_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 164, in async_force_update_all
    await self.hass.async_add_executor_job(
        self.vehicle_manager.force_refresh_all_vehicles_states
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 134, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(vehicle_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 139, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 297, in force_refresh_vehicle_state
    tz = detect_timezone_for_date(last_updated_at, ref_date, CA_TIMEZONES)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/utils.py", line 107, in detect_timezone_for_date
    delta = (ref_date - date.replace(tzinfo=tz)).total_seconds()
             ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by cdnninja** [comment]
@Lekensteyn looks like the timezone code doesn't function.   Would you be able to take a look?

**Comment by Lekensteyn** [comment]
The crash reported above was introduced with hyundai_kia_connect_api v3.45.2, included with kia_uvo 2.45.1 via commit e56cfa9c04de. It should be fixed by https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/908 (unreleased).

Side note: https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/51d034a18d9caa8a64c638f001347f8d9a32d4d3/custom_components/kia_uvo/requirements.txt got out of sync with manifest.json, should requirements.txt be deleted?


> Timezone is GMT-07:00
> 
> To keep the log short I removed some information that I thought was irrelevant to this issue.

Do you have any other timezone or date-related field in the API response? Is there a `transaction` field with an `apiStartDate` and `apiEndDate` subfields?

> ```
> 2025-09-23 08:43:18.947 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received forced vehicle data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20250923144317', '
> 2025-09-23 08:43:18.948 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Offset between vehicle and UTC: 0 hours
> 2025-09-23 08:43:18.948 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: 2025-09-23 14:16:26-06:00
> 2025-09-23 08:43:18.949 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2025-09-23 14:16:26-06:00
> ```

The difference between the local logging timestamp and the remote lastStatusDate is 6 hours (minus 1 second). Is the timezone really UTC-0700 (Canada/Mountain, summer time)? Or UTC-0600 (Canada/Central, summer time).

What is the timezone configured in the car?

**Comment by etam** [comment]
At least for me it looks like it's resolved.

**Comment by rwelsh09** [comment]
Still an issue for me.

<img width="837" height="1356" alt="Image" src="https://github.com/user-attachments/assets/484afdd8-ec9e-40bb-9c46-09874e22c83d" />
