### ISSUE TITLE
Set temperature 2°C lower in my car.

### ISSUE THREAD

**Issue by zadigre** [Hyundai-Kia-Connect/kia_uvo#220]
I’m in Canada
I have a 2021 Kona Electric

When I start climate, temperature set in the car is 2°C lower.
Temperature shown in HA is same what I’ve set in with start climate. But when I go in my car, it’s 2 lower.

When using the Bluelink app, it’s set properly in my car.

i set it 2 higher in HA and it’s set at my desired temperature.

**Comment by cdnninja** [comment]
I will do another test on my car, assuming it works for me this means the temp range is different on the Hyundai car's vs Kia.  It should be a quick fix.  Thanks for raising it.

**Comment by dallaby23** [comment]
Hi.. first off.. thanks so much for your hard work on this.. I have been using it for awhile now and love the ability to finally start my car.. lol.. I also created a node-red to check for locked then following that command start the vehicle.. works awesome.. 
The reason I jumped in here is I am also in Canada with a Kia Seltos 2021 and when I start_climate with temperature it always sets the temp in the car to 22.5 .. I have tried to start with service set to 24 and 24.5 and 24.0 still always sets it to 22.5 ... Heated steering wheel works fine and front/rear defrost all seem to work fine.. I will try and grab the log and drop it here..

**Comment by cdnninja** [comment]
Hoping to grab time with my wife's car to test this out.  If I can replicate it will be a quick fix. Could I confirm what version you are running?

**Comment by dallaby23** [comment]
1.2.5 .. I just updated before testing this evening..

**Comment by zadigre** [comment]
@cdnninja 
As soon as you release something on the master branch, I’lol test it 😉

**Comment by cdnninja** [comment]
I tested it out.  In my single test using the default values in home assistant my car started but 0.5C off.  I have found a potential bug in the math that impacts 22C only.  Have you tried other temps to see if this impacts multiple temps?  If it is multiple I may need you to capture details from a web browser to see what Kia / Hyundai is passing to start the car.  This could be an electric car issue, I have an ICE.

**Comment by zadigre** [comment]
@cdnninja 
it's happening with multiple temperature for me. 
I usually use 19.5 in Bluelink app. If I try with the same temperature in HA, it will set to 17.5 in the car. I actually do not see it in the car at this temperature (the screen is off), but next time I turn on my car, temperature is at 17.5. 
After finding out about the 2°C difference, I set it to 21.5. and I've got 19.5 in my car.

**Comment by cdnninja** [comment]
Could you start the car via your webbrowser with correct settings? Ideally as close to HA defaults as possible while doing this: 
https://github.com/fuatakgun/kia_uvo/wiki/How-to-sniff-API-via-MS-Edge You are looking for a section that will look like:         payload = {
            "hvacInfo": {
                "airCtrl": int(climate),
                "defrost": defrost,
                "heating1": int(heating),
                "airTemp": {
                    "value": set_temp,
                    "unit": 0,
                    "hvacTempType": 1,
                },
            },
            "pin": self.pin,

**Comment by dallaby23** [comment]
I can see my temperature when I look through the window when I start it and
mine is always 2 degrees lower..

**Comment by cdnninja** [comment]
Actually a potentially easier way to check this.  In your app what range of options do you have for temp?  Our code is using 16-32 in 0.5 increments.  Do you see 14 as an option?

**Comment by zadigre** [comment]
@cdnninja 
in the app and on mybluelink.ca, I have 17-27 in 0.5 increments.

**Comment by zadigre** [comment]
@cdnninja 

when setting temp to 19.5 on mybluelink

hvacInfo: {airCtrl: 1, defrost: true, airTemp: {value: "0BH", unit: 0, hvacTempType: "1"}, heating1: 0}
airCtrl: 1
airTemp: {value: "0BH", unit: 0, hvacTempType: "1"}
hvacTempType: "1"
unit: 0
value: "0BH"
defrost: true
heating1: 0
pin: "XXXX"

**Comment by dallaby23** [comment]
So for my kia seltos there is a slider with "lo" at the min and "hi" at the
max.. in between I can set between 17.0-27.0 in .5 increments..

**Comment by cdnninja** [comment]
Perfect that is exactly what I need.  It looks like your EV cars use the same range as what we found for EU EV which is different than Canadian ICE cars.   I will see if I can code something up quick before I head out.  If not this may be tonight or in a few days.

**Comment by dallaby23** [comment]
Sorry my car is a gas 2021 Kia Seltos .. not EV..

**Comment by cdnninja** [comment]
#224 will solve this for an EV @zadigre could you replace your Canada API file with it to test?  

@dallaby23 this means they have changed temperature ranges on cars, now we have to figure out which cars and how to detect this.  Mine is a 2019 Sorento ICE.  This could be a generation of the UVO system, or the year.

**Comment by zadigre** [comment]
@cdnninja 
is it available in Master branch directly?

FYI, Here’s the info for 17°C
hvacInfo: {airCtrl: 1, defrost: true, airTemp: {value: "06H", unit: 0, hvacTempType: 1}, heating1: 0}

And 27°C
hvacInfo: {airCtrl: 1, defrost: true, airTemp: {value: "1AH", unit: 0, hvacTempType: 1}, heating1: 0}

**Comment by cdnninja** [comment]
No it is under #224 so you will need to copy paste the one file.

**Comment by cdnninja** [comment]
@dallaby23 could you use the same sniff from above? I'm wondering if the temptype is the key. I have only seen that being different on an EV but if yours is 1 as well that may be it.

**Comment by zadigre** [comment]
@cdnninja 
looks like it's working as intended now with the new file. I tried my my 19.5 setting in HA... and car was set at 19.5.
I'll let you know if I encounter any other problem.

**Comment by cdnninja** [comment]
Could each of you also confirm on a start that the temp sensor displayed in home assistant is wrong?  Just want to confirm that. This only works while car is running otherwise will show a low number: 
![image](https://user-images.githubusercontent.com/6373468/147391240-dcc9c5d4-47a3-475e-9255-b3fcfd3742e3.png)

**Comment by zadigre** [comment]
@cdnninja 
<img width="349" alt="Capture d’écran, le 2021-12-25 à 13 24 35" src="https://user-images.githubusercontent.com/4810599/147391298-804d5aa0-850f-40d2-bc44-bc060d93288a.png">

so I guess the translation here is not done properly.

**Comment by zadigre** [comment]
@cdnninja 
and also when I set the temperature to 19.5 on mybluelink or Bluelink app, set temperature is also shown as 21.5

**Comment by dallaby23** [comment]
Out doing some Christmas stuff so might not be available till tomorrow..

**Comment by cdnninja** [comment]
> @cdnninja 
> 
> and also when I set the temperature to 19.5 on mybluelink or Bluelink app, set temperature is also shown as 21.5 in HA

Yes I'll need to update that logic as well.  I'll wait to see if we can find out why your two cars are different than mine.

**Comment by dallaby23** [comment]
k.. quick test.. started 2021 Kia Seltos Canada.. car shows 21.. Set
Temperature in HA shows 23.. Air Temp value shows 0EH and unit is 0 .. Air
Temp unit is C ...

**Comment by cdnninja** [comment]
Yes the range is different for your car.  I am interested to see what the website sends and what hvacTempType is set to.

**Comment by cdnninja** [comment]
Basically the way it works is it send a hex number that is just the index of the temp from a list.   Your list seems to be 2 degree different than mine. Need to find a way to predict it so we can get it right for both cars. Could we also get the data for yours from the data element in home assistant?

**Comment by zadigre** [comment]
@cdnninja 
do you need anything else from me or we are all set for now?

**Comment by cdnninja** [comment]
> @cdnninja 
> 
> do you need anything else from me or we are all set for now?
> 
> 

Good for now. Thank you!  Hyundai and Kia we are finding are interesting. Very little consistency.

**Comment by cdnninja** [comment]
@zadigre  could I actually get the message that state "Get Vehicles Response " from your debug logs? Specifically looking to see what "genType" is.

**Comment by zadigre** [comment]
@cdnninja 

here's what I've got after starting climate :
2021-12-25 18:36:40 DEBUG (SyncWorker_4) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received Pin validation response <Response [200]>
2021-12-25 18:36:42 DEBUG (SyncWorker_4) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received start_climate_ev response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}
2021-12-25 18:37:01 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Last action_status: 200
2021-12-25 18:37:15 DEBUG (SyncWorker_0) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20211225233651', 'airCtrlOn': True, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '0BH', 'unit': 0}, 'defrost': True, 'acc': False, 'evStatus': {'batteryCharge': True, 'batteryStatus': 63, 'batteryPlugin': 2, 'remainTime2': {'etc1': {'value': 99, 'unit': 1}, 'etc2': {'value': 1400, 'unit': 1}, 'etc3': {'value': 300, 'unit': 1}, 'atc': {'value': 280, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 196.0, 'unit': 1}, 'totalAvailableRange': {'value': 196.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 1, 'sideBackWindowHeat': 1, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 83, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2021-12-25 18:37:18 DEBUG (SyncWorker_0) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 12920.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20211109', 'imatServiceOdometer': 24920.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20220509', 'currentOdometer': 17194.9, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 12000.0, 'serviceDaysDuration': 180, 'serviceMonthsThreshold': 6}}}
2021-12-25 18:37:18 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - LastUpdated 2021-12-25 23:36:51+00:00 - Timezone UTC
2021-12-25 18:37:18 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Engine type set VEHICLE_ENGINE_TYPE.EV

**Comment by cdnninja** [comment]
The get vehicle response comes on first login or token renewal.

**Comment by zadigre** [comment]
here's everything... not sure what you are looking for exactly. 


2021-12-25 18:32:51 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - async_setup_entry started - <homeassistant.config_entries.ConfigEntry object at 0x7f92aa7e00>
2021-12-25 18:32:51 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Received token into Vehicle Object {'valid_until': '2021-12-26 05:12:54.049911', 'access_token': 'eyJlbmMiOiJreVJMMEc2SEVPY1ZNdFl2a2pHdmRGRXN6RzJGemYySGw4eFJzYzRFelA3amlxcC80aXBNN0RueXFuRUVIYzhDdFJ2UkRGbXRZV0E1L3N2VjZzMHZYbnBUTnpMUlZjelZXbEVsemRZaDVZQ0g4WFI5RFpRL1FHT0YwZ0dVNURSMFU1OWtuNlB3S3gvYUtSVEVlYXFvOXhxSEppMllaY0E5Z0g4V0QyeWk1OS9uakF5Tm51Q1RHL3NlQnlRSEFHWXBabFFzZEQrL2JiWFhiR0ZiSnpVc1ZoZG5IMWZJcXRpTEJoNzhHVWNQYUxYRGVNUjE2M1RBbm9FdTFuaHJhNFNGeTU4bnZoMk5zRnpTZWx4bzZ4TGFoZEVvUU1QcW9lUFM5a1FXTTg1dGY3dUZITjliZGNVVHpOWWMwTjRZZEtYUmZwY2hZNTlqbzEyaFg2UHYraDVQSzZSc055dlhvVDkyQWxKK1U5ZGo3aGt1aU1tVDcycSs4dlNheGl3U1Y0VUd6NndJR0lpWU5XUGdGSlQzaURTang3M3BySXRxNi9jUlA0RFJ5UUQzK2oxazZaakw5R04zby9TdmJ1ZEZZRDJKR0pKN2ZjNW1NZXFLMG56SWlPbmtGdzlBREt6RGNoeTJoQlpFUWJkc2x0V0RZLzRzZ0JDTjF5M3Z3ZmxrdzFsYitsWlBIZXhYa1B3MmpwTnc1V0ZIN0pJSW1yRFFLUmRVR0tLTWUvN1Vsd3ZrbjljNTZaeEx0VEk0L0piMUFtTkNnMUVmUktIN2xIS0hwTUFpSG53SmxQWVZHYjAvQzl3ek1ML0t0R3YrQTZZWHgyRzNuQVp1d0tybm9DQkpQNmZzblZpS3ZEYnRuaW05ZCthT3d5QkM0TmU2K1g2NUhMbXRwN2NKME5BaC8xUEVQMnkxd3lDUWFodHR3TXU0R3QvMkllMjhnOHNTbXM0Rkp3RElqTkpwalJoUWJZQUJhOW9kRXlwcEc2MmI4U0tFNXNYdzJOdU1ncHEwWTFHbXovcnUzUVg5Q2x3R3NLR2xXWlNXdXdQU0J0UE9SQll2VjBZaE5kcGtsVVBBa09OVnZIQUo5cnY4R2RiaUMxemNjVCtPbVMxZjhMKzN4TythTUg3REYyeU9rTHdJY3dGdEJRMzlPTDhRWUZqZUNkdjhiMGtBcWFGZWpBWkdVTG5QU0ZVUjFrSXBrUm44YkRtbHptWFYvWm1TMHd6RVByY3NmZWNNUDd2cnk5ZkU2QVp1SGlFMlhDdmtkYTUwVHhxT2doMmU0NFg4UmVkWUtVamJ0YXphQXJueWtxYmJkTG9EbVRTWjQyWUp4TGVoRUNVVUlGdTZvNjE1Y01HQ2ZUUG1vK0hscjBON0ZtcWdyU3czWThZWHZ5Rjh3dmhzTU1iaFZ5MS9LTUJNVjViWVQ0Zz0iLCJrZXkiOiJKcDBPZ2RDRnp1L3pJWkdyR2g3dUliRVg4d2pidHJqeXVvcFUzVmIwejhJcjJDc0E3TTUycnBkZG9WT2haSUo0eC9xb1hxejFXdU91RzNWSEEreVV6QT09In0=', 'refresh_token': 'eyJlbmMiOiJKK3FwTnFEbnowYU9FNE4vcmJMZzgzN0NTcUhZMlR5Q0RROFVaY2lUdXpRYW95Rmg1VXhKck1ucjBQUjdjTXM1M0VoVnFJY0FLTVpDanJvVjg4UklJN2FWSVNpRUk3ZTJCVUpxRU5MWVV0OVN5Y0V5VWptc3FKTDg2NXNmNWlEeHpKTElHRXlsT1ZXakxwUkRUZFZwT3VSRkJwVEl6VzgwVXlOMVpEMVZiSVFETWx2QW5KVHIzUlpXSVdZNk9HdUdVOUovcFRSRG53b2M5Q0pUMTJEdm1ENlFVYzBaR2tBMUlja3VsZUxrbDlXU1hlZjQrdzh6U2JoTGxoMUFyWi9CSldhNGRXOVRsTENvZk9nOXFGY0g1OWNCV2FUMXlJTTBiUlhnbmRMMlFOeFhQdnhlOVo2WkY0OUhPVk1BZmpxR3N5SjVhQ0MyblVWaXpCOXZFaUp4T2x3aVpId2pDYVZQTUJJcVROUEVHZkYrZXZuazM5ZFFtQWh3dWFLcElBdWNnY2xXNnN6M1REeUZmeVdRMXRJcG9ueERWdlo0K0d3RGdYdUlhM0hwWTFEWjhNanIwSXZzcmk3VWs4UmVnTFl1eFNpdmJWT0NkMUV2d0NGUzI1QkZyUHUvRWNlNHVEVzVHZy9Ta3BlWTVOc3YzVWo4UkFkYk50OFlXa1hnQklFSkxuSTV6OHFtMlN0NnZIbkpvdzdRNFpYRUUvazIwZDVrckRCUTgvNWw0bVo1KzJCRFpPakh3a1QrODNFeTIrU2pCQjR5OWxWMFZHeWtaQVZiQVZlL25mc0w4WENSeThFbGVoRmJ5Y0JUUElOaFlWTzVMTDVQbDFnTmZGZTYrVlZxVzVtazlzZVdSZ2VmT2FXdHhoVThKSHRhTUo2N3JQN0xBWUdvM2k5SHR0a1RYSGx0VURuY1F0SXJUQThRZjZJdnEybGtibXlUTlRkYlVqU1V5a3lJbFZmU1FhRW5FUkVsaUZ2N1lWUEdWdnhyeUpCMlB1RzdNbkhLc09IVjlSVnFpeFUvSllIbHErMWprbzRHdTJ3UlNzWTFvN2dZSVQ4c0tGYmp0NVkrUkdEQUZNaEZNVlhySHptVUx6Q3dKVm1kSVlwQXN2WEh1VFcyWkY5TFRSa01SRXBSZGlWQ2lBVzkvNFdLeGgvdE1hdjZETlJmbmd0aG1WS2VhYWlLSTRUMXJraWZqc2VGTkJSU3dMQllNQ1FGVGl0bjZ4M054QThDMmxHWTA2T3lSQ3FIVjRSRTFFdjVBb2t0MzlpWVZZbVB3UlZXU3UvSVUrWE5ubmdaUlVpT1duUUVFam5zYzlCNmt6L3QyNENFK3g2dHMxcHZEWXJOdmN6M3U1SmVCTG5EZWNwTVV0Vng3QWkwZ0pLdDlhdjhpUEFHeGoveTF1eWFBc3ZyTVc5T2U4MD0iLCJrZXkiOiJWRlhvdEZWUGhDUldLSUF6MFpJMnVDVlNoRjBjclltWCtiTzNQa0ZSbnU1OW9LenRlSEFoUXJXQXcxNkxZYVh3NjV6eU5tZndmK2w1KzJzRFFGS240dz09In0=', 'device_id': None, 'vehicle_name': 'Kona VÉ', 'vehicle_id': 'qLHNk/TY2fGJeLL1FVGDXA==', 'vehicle_regid': None, 'vehicle_model': 'Kona VÉ', 'vehicle_registration_date': 'missing', 'stamp': 'NoStamp'}
2021-12-25 18:32:51 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Refresh token started 2021-12-26 05:12:54.049911 2021-12-25 18:32:51.904872 False
2021-12-25 18:33:07 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20211225232342', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '00H', 'unit': 0}, 'defrost': False, 'acc': False, 'evStatus': {'batteryCharge': True, 'batteryStatus': 61, 'batteryPlugin': 2, 'remainTime2': {'etc1': {'value': 104, 'unit': 1}, 'etc2': {'value': 1470, 'unit': 1}, 'etc3': {'value': 320, 'unit': 1}, 'atc': {'value': 295, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 216.0, 'unit': 1}, 'totalAvailableRange': {'value': 216.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'sideBackWindowHeat': 0, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 83, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2021-12-25 18:33:10 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 12920.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20211109', 'imatServiceOdometer': 24920.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20220509', 'currentOdometer': 17194.9, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 12000.0, 'serviceDaysDuration': 180, 'serviceMonthsThreshold': 6}}}
2021-12-25 18:33:13 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received Pin validation response <Response [200]>
2021-12-25 18:33:20 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Get Vehicle Location {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'head': 218, 'coord': {'lat': 45.579855, 'lon': -73.516379, 'alt': 10.04, 'type': 0}, 'accuracy': {'hdop': 0, 'pdop': 1}, 'time': '20211225233317', 'speed': {'value': 0, 'unit': 0}}}
2021-12-25 18:33:20 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - LastUpdated 2021-12-25 23:23:42+00:00 - Timezone UTC
2021-12-25 18:33:20 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Engine type set VEHICLE_ENGINE_TYPE.EV
2021-12-25 18:33:20 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.targetSOClevel
2021-12-25 18:33:20 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.targetSOClevel
2021-12-25 18:33:20 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.dte.rangeByFuel.totalAvailableRange.value
2021-12-25 18:33:20 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.dte.rangeByFuel.totalAvailableRange.value
2021-12-25 18:33:20 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleLocation.geocodedLocation.display_name
2021-12-25 18:36:40 DEBUG (SyncWorker_4) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received Pin validation response <Response [200]>
2021-12-25 18:36:42 DEBUG (SyncWorker_4) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received start_climate_ev response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}}
2021-12-25 18:37:01 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Last action_status: 200
2021-12-25 18:37:15 DEBUG (SyncWorker_0) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20211225233651', 'airCtrlOn': True, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '0BH', 'unit': 0}, 'defrost': True, 'acc': False, 'evStatus': {'batteryCharge': True, 'batteryStatus': 63, 'batteryPlugin': 2, 'remainTime2': {'etc1': {'value': 99, 'unit': 1}, 'etc2': {'value': 1400, 'unit': 1}, 'etc3': {'value': 300, 'unit': 1}, 'atc': {'value': 280, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 196.0, 'unit': 1}, 'totalAvailableRange': {'value': 196.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 1, 'sideBackWindowHeat': 1, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 83, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2021-12-25 18:37:18 DEBUG (SyncWorker_0) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 12920.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20211109', 'imatServiceOdometer': 24920.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20220509', 'currentOdometer': 17194.9, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 12000.0, 'serviceDaysDuration': 180, 'serviceMonthsThreshold': 6}}}
2021-12-25 18:37:18 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - LastUpdated 2021-12-25 23:36:51+00:00 - Timezone UTC
2021-12-25 18:37:18 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Engine type set VEHICLE_ENGINE_TYPE.EV

**Comment by cdnninja** [comment]
Try restarting home assistance and try searching for the strings I mentioned earlier.

**Comment by zadigre** [comment]
I don't see this specific string. 
nothing different. 


2021-12-25 21:14:12 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - async_setup_entry started - <homeassistant.config_entries.ConfigEntry object at 0x7f9d38ee00>
2021-12-25 21:14:12 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Received token into Vehicle Object {'valid_until': '2021-12-26 05:12:54.049911', 'access_token': 'eyJlbmMiOiJreVJMMEc2SEVPY1ZNdFl2a2pHdmRGRXN6RzJGemYySGw4eFJzYzRFelA3amlxcC80aXBNN0RueXFuRUVIYzhDdFJ2UkRGbXRZV0E1L3N2VjZzMHZYbnBUTnpMUlZjelZXbEVsemRZaDVZQ0g4WFI5RFpRL1FHT0YwZ0dVNURSMFU1OWtuNlB3S3gvYUtSVEVlYXFvOXhxSEppMllaY0E5Z0g4V0QyeWk1OS9uakF5Tm51Q1RHL3NlQnlRSEFHWXBabFFzZEQrL2JiWFhiR0ZiSnpVc1ZoZG5IMWZJcXRpTEJoNzhHVWNQYUxYRGVNUjE2M1RBbm9FdTFuaHJhNFNGeTU4bnZoMk5zRnpTZWx4bzZ4TGFoZEVvUU1QcW9lUFM5a1FXTTg1dGY3dUZITjliZGNVVHpOWWMwTjRZZEtYUmZwY2hZNTlqbzEyaFg2UHYraDVQSzZSc055dlhvVDkyQWxKK1U5ZGo3aGt1aU1tVDcycSs4dlNheGl3U1Y0VUd6NndJR0lpWU5XUGdGSlQzaURTang3M3BySXRxNi9jUlA0RFJ5UUQzK2oxazZaakw5R04zby9TdmJ1ZEZZRDJKR0pKN2ZjNW1NZXFLMG56SWlPbmtGdzlBREt6RGNoeTJoQlpFUWJkc2x0V0RZLzRzZ0JDTjF5M3Z3ZmxrdzFsYitsWlBIZXhYa1B3MmpwTnc1V0ZIN0pJSW1yRFFLUmRVR0tLTWUvN1Vsd3ZrbjljNTZaeEx0VEk0L0piMUFtTkNnMUVmUktIN2xIS0hwTUFpSG53SmxQWVZHYjAvQzl3ek1ML0t0R3YrQTZZWHgyRzNuQVp1d0tybm9DQkpQNmZzblZpS3ZEYnRuaW05ZCthT3d5QkM0TmU2K1g2NUhMbXRwN2NKME5BaC8xUEVQMnkxd3lDUWFodHR3TXU0R3QvMkllMjhnOHNTbXM0Rkp3RElqTkpwalJoUWJZQUJhOW9kRXlwcEc2MmI4U0tFNXNYdzJOdU1ncHEwWTFHbXovcnUzUVg5Q2x3R3NLR2xXWlNXdXdQU0J0UE9SQll2VjBZaE5kcGtsVVBBa09OVnZIQUo5cnY4R2RiaUMxemNjVCtPbVMxZjhMKzN4TythTUg3REYyeU9rTHdJY3dGdEJRMzlPTDhRWUZqZUNkdjhiMGtBcWFGZWpBWkdVTG5QU0ZVUjFrSXBrUm44YkRtbHptWFYvWm1TMHd6RVByY3NmZWNNUDd2cnk5ZkU2QVp1SGlFMlhDdmtkYTUwVHhxT2doMmU0NFg4UmVkWUtVamJ0YXphQXJueWtxYmJkTG9EbVRTWjQyWUp4TGVoRUNVVUlGdTZvNjE1Y01HQ2ZUUG1vK0hscjBON0ZtcWdyU3czWThZWHZ5Rjh3dmhzTU1iaFZ5MS9LTUJNVjViWVQ0Zz0iLCJrZXkiOiJKcDBPZ2RDRnp1L3pJWkdyR2g3dUliRVg4d2pidHJqeXVvcFUzVmIwejhJcjJDc0E3TTUycnBkZG9WT2haSUo0eC9xb1hxejFXdU91RzNWSEEreVV6QT09In0=', 'refresh_token': 'eyJlbmMiOiJKK3FwTnFEbnowYU9FNE4vcmJMZzgzN0NTcUhZMlR5Q0RROFVaY2lUdXpRYW95Rmg1VXhKck1ucjBQUjdjTXM1M0VoVnFJY0FLTVpDanJvVjg4UklJN2FWSVNpRUk3ZTJCVUpxRU5MWVV0OVN5Y0V5VWptc3FKTDg2NXNmNWlEeHpKTElHRXlsT1ZXakxwUkRUZFZwT3VSRkJwVEl6VzgwVXlOMVpEMVZiSVFETWx2QW5KVHIzUlpXSVdZNk9HdUdVOUovcFRSRG53b2M5Q0pUMTJEdm1ENlFVYzBaR2tBMUlja3VsZUxrbDlXU1hlZjQrdzh6U2JoTGxoMUFyWi9CSldhNGRXOVRsTENvZk9nOXFGY0g1OWNCV2FUMXlJTTBiUlhnbmRMMlFOeFhQdnhlOVo2WkY0OUhPVk1BZmpxR3N5SjVhQ0MyblVWaXpCOXZFaUp4T2x3aVpId2pDYVZQTUJJcVROUEVHZkYrZXZuazM5ZFFtQWh3dWFLcElBdWNnY2xXNnN6M1REeUZmeVdRMXRJcG9ueERWdlo0K0d3RGdYdUlhM0hwWTFEWjhNanIwSXZzcmk3VWs4UmVnTFl1eFNpdmJWT0NkMUV2d0NGUzI1QkZyUHUvRWNlNHVEVzVHZy9Ta3BlWTVOc3YzVWo4UkFkYk50OFlXa1hnQklFSkxuSTV6OHFtMlN0NnZIbkpvdzdRNFpYRUUvazIwZDVrckRCUTgvNWw0bVo1KzJCRFpPakh3a1QrODNFeTIrU2pCQjR5OWxWMFZHeWtaQVZiQVZlL25mc0w4WENSeThFbGVoRmJ5Y0JUUElOaFlWTzVMTDVQbDFnTmZGZTYrVlZxVzVtazlzZVdSZ2VmT2FXdHhoVThKSHRhTUo2N3JQN0xBWUdvM2k5SHR0a1RYSGx0VURuY1F0SXJUQThRZjZJdnEybGtibXlUTlRkYlVqU1V5a3lJbFZmU1FhRW5FUkVsaUZ2N1lWUEdWdnhyeUpCMlB1RzdNbkhLc09IVjlSVnFpeFUvSllIbHErMWprbzRHdTJ3UlNzWTFvN2dZSVQ4c0tGYmp0NVkrUkdEQUZNaEZNVlhySHptVUx6Q3dKVm1kSVlwQXN2WEh1VFcyWkY5TFRSa01SRXBSZGlWQ2lBVzkvNFdLeGgvdE1hdjZETlJmbmd0aG1WS2VhYWlLSTRUMXJraWZqc2VGTkJSU3dMQllNQ1FGVGl0bjZ4M054QThDMmxHWTA2T3lSQ3FIVjRSRTFFdjVBb2t0MzlpWVZZbVB3UlZXU3UvSVUrWE5ubmdaUlVpT1duUUVFam5zYzlCNmt6L3QyNENFK3g2dHMxcHZEWXJOdmN6M3U1SmVCTG5EZWNwTVV0Vng3QWkwZ0pLdDlhdjhpUEFHeGoveTF1eWFBc3ZyTVc5T2U4MD0iLCJrZXkiOiJWRlhvdEZWUGhDUldLSUF6MFpJMnVDVlNoRjBjclltWCtiTzNQa0ZSbnU1OW9LenRlSEFoUXJXQXcxNkxZYVh3NjV6eU5tZndmK2w1KzJzRFFGS240dz09In0=', 'device_id': None, 'vehicle_name': 'Kona VÉ', 'vehicle_id': 'qLHNk/TY2fGJeLL1FVGDXA==', 'vehicle_regid': None, 'vehicle_model': 'Kona VÉ', 'vehicle_registration_date': 'missing', 'stamp': 'NoStamp'}
2021-12-25 21:14:12 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Refresh token started 2021-12-26 05:12:54.049911 2021-12-25 21:14:12.487724 False
2021-12-25 21:14:26 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20211226014044', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '00H', 'unit': 0}, 'defrost': False, 'acc': False, 'evStatus': {'batteryCharge': True, 'batteryStatus': 80, 'batteryPlugin': 2, 'remainTime2': {'etc1': {'value': 58, 'unit': 1}, 'etc2': {'value': 760, 'unit': 1}, 'etc3': {'value': 180, 'unit': 1}, 'atc': {'value': 150, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'gasModeRange': {'value': 0.0, 'unit': 1}, 'evModeRange': {'value': 291.0, 'unit': 1}, 'totalAvailableRange': {'value': 291.0, 'unit': 1}}, 'type': 2}]}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'sideBackWindowHeat': 0, 'dte': {}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 83, 'batState': 0, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2021-12-25 21:14:29 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 12920.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20211109', 'imatServiceOdometer': 24920.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20220509', 'currentOdometer': 17194.9, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 12000.0, 'serviceDaysDuration': 180, 'serviceMonthsThreshold': 6}}}
2021-12-25 21:14:33 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Received Pin validation response <Response [200]>
2021-12-25 21:14:41 DEBUG (SyncWorker_3) [custom_components.kia_uvo.KiaUvoApiCA] kia_uvo - Get Vehicle Location {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'head': 220, 'coord': {'lat': xxx, 'lon': xxx, 'alt': 13.64, 'type': 0}, 'accuracy': {'hdop': 0, 'pdop': 1}, 'time': '20211226021438', 'speed': {'value': 0, 'unit': 0}}}
2021-12-25 21:14:41 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - LastUpdated 2021-12-26 01:40:44+00:00 - Timezone UTC
2021-12-25 21:14:41 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Engine type set VEHICLE_ENGINE_TYPE.EV
2021-12-25 21:14:41 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.targetSOClevel
2021-12-25 21:14:41 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.targetSOClevel
2021-12-25 21:14:41 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.dte.rangeByFuel.totalAvailableRange.value
2021-12-25 21:14:41 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.dte.rangeByFuel.totalAvailableRange.value
2021-12-25 21:14:41 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleLocation.geocodedLocation.display_name

**Comment by zadigre** [comment]
my last message was after a restart of home assistant. the message before was after a restart of the host os. 

I also tried to reload the integration... and I get the same log file

**Comment by zadigre** [comment]
I guess #224 has not been included in 1.2.6 release?

**Comment by fuatakgun** [comment]
This PR is still open, i believe @cdnninja is still figuring out what is the main point to differentiate temperature range. Yes, it is not part of latest release.

**Comment by cdnninja** [comment]
@zadigre  are you able to restart again and search for "Get Vehicles Response"?  It for sure happens when login occurs. It could be that the token wasn't expired above so it didn't try log in.  @dallaby23 this is something you could help with as well.  

@fuatakgun  is right - at this point I don't know why your cars are different than mine, I need to find a reason so we can have this work for both our cars.

**Comment by dallaby23** [comment]
Not sure if I am missing something but I don't see hvactemptype at all in
my home assistant logs..

**Comment by cdnninja** [comment]
Two separate things we were looking for. hvactemptype won't be in the logs as we currently don't log it.   The above post was from sniffing the connection to Hyundai / Kia.   At this point I want to focus on "Get Vehicles Response" as it holds something called gentype that for my car is G1, thinking yours may report G2 or something like that.  This may be my clue.

**Comment by dallaby23** [comment]
Mine is reporting G1 for gentype

**Comment by zadigre** [comment]
@cdnninja 
I still do not see what you are looking for in my log.
Token is expiring 2021-12-28 03:16:21.539661
So I guess i la get have to wait a few hours before seeing it.
Will it automatically appear in the log when it automatically refreshes the token?

**Comment by cdnninja** [comment]
Yes it will show up assuming debug is enabled.   Considering dallaby23 is G1 I don't think that will help us.  Maybe this is just a 2021 thing?  I could assume it impacts all 2021 and wait until I get a complain of it being 2C wrong in the other direction.

**Comment by zadigre** [comment]
@cdnninja 
I have this in my config file... 
logger:
  default: warning
  logs:
    custom_components.kia_uvo: debug

anything else I should add?

is the valid_until date&time in GMT?

**Comment by cdnninja** [comment]
@Kevr0n228 What year is your car and do you have this issue? 
@zadigre yes that is correct for debug.   As for time I think that one is local time - that is something we should clarify in the logs.

**Comment by Kevr0n228** [comment]
I've got a 2019 and it seems I have the same issue. Just set the climate at 22 degC, but the Homeassistant Bluelink shows the set temperature as 24.

**Comment by cdnninja** [comment]
@kevr0n228  thanks for confirming.  Just to clarify so when you did a remote start for 22 and went to look it was at 20?  Or did you set at 24 and car went to 22 with bluelink showing 24 as well?

**Comment by Kevr0n228** [comment]
I'm actually just finishing a charge while driving home. I was waiting in
the car with the climate set to 22 when I checked my email. I VPN'd into
home and checked hass where it said 24. I have not checked whether the
temperature I use when I call `start_climate` also comes up with a 2 degree
difference. I can take a look later once I'm done the drive.

**Comment by zadigre** [comment]
@cdnninja 
my genType is G3.

**Comment by cdnninja** [comment]
Once @Kevr0n228 confirms on a start command his is two off that means this seems to be all EVs in Canada plus at least 2021 ICE cars.  This is my current theory atleast.

**Comment by zadigre** [comment]
@Kevr0n228 
any news? we are all waiting for you! 😉

**Comment by Kevr0n228** [comment]
Sorry for the delay, I've been trying to test but for some reason my set temperature is just stuck at 16. Not sure if I'm not waiting long enough but running a forced update doesn't seem to do it either.

**Comment by cdnninja** [comment]
Which version are you on?  I put in a fix that would cause this for certain temps but that is only for read. Not for starting.

**Comment by Kevr0n228** [comment]
I'm on v1.24 currently

**Comment by cdnninja** [comment]
The newer version solves a reading issue for 22c. The version doesn't change remote start though.  Just the sensor view.

**Comment by Kevr0n228** [comment]
Alright, updating to v1.26 got the set temperature to update after calling start_climate_ev. No discrepancy this time, requested 22C, got 22C.

**Comment by cdnninja** [comment]
Sounds good, thanks for checking.  In car showed the same values? 

I’m going to assume the 2c issue is a 2021 and newer thing.

**Comment by unsoluble** [comment]
For what it's worth, am seeing the 2c discrepancy here on a 2020 Kona electric. Am running newer than 1.2.6 for sure, as I just set this up a few days ago.

**Comment by cdnninja** [comment]
@unsoluble  great info.  So that means it is potentially 2020 and newer.

**Comment by cdnninja** [comment]
I have been spending most of my time here working on version 2.0 of this integration.   This issue is easy to resolve in that version.   Is it okay if we leave this for 2.0?

**Comment by cdnninja** [comment]
Closing as per #386

**Comment by cdnninja** [comment]
Resolved in 2.0

**Comment by unsoluble** [comment]
For what it's worth, I'm still seeing this discrepancy as of 2.0.49 (in a 2020 Kona E). Car temp still ends up 2° cooler than instructed by HA scripts.

**Comment by cdnninja** [comment]
@unsoluble  Is this a Canadian car?

**Comment by unsoluble** [comment]
Ahh, okay, thanks! :)

**Comment by cdnninja** [comment]
If you update from "master" in HACS this should be fixed for you. Next release version number will include it.

**Comment by cdnninja** [comment]
@unsoluble  are you able to let me know if not solved. I will close for now.

**Comment by unsoluble** [comment]
Yep, works, thanks! Heated seats don't, as far as I can tell, but that's something for another ticket. :)

**Comment by cdnninja** [comment]
> Yep, works, thanks! Heated seats don't, as far as I can tell, but that's something for another ticket. :)

We have a thread for that new feature.  Would love feedback and logs on this.  I know the underlying api works but I don't have a car with support for this to test it all out.

**Comment by dallaby23** [comment]
Temperature is correct on my 2021 kia seltos.. I am in Canada as well..

**Comment by Kevr0n228** [comment]
I just started using the preheat on my 2019 Electric Kona (Canada) again and it seems that this issue has returned. I'm running the latest version of the integration, updated it this morning.  I tried requesting several different temperatures. The set temperature in homeassistant was the same as what I requested, just the actual set temp in the car (and what was shown in the bluelink app) was 2 degrees lower.

**Comment by zadigre** [comment]
I just tired it on my 2021 Kona Electric (also in Canada)… and it works as intended (same temperature is showing everywhere).Le 7 nov. 2023 à 20:07, Kevin ***@***.***> a écrit :﻿
I just started using the preheat on my 2019 Electric Kona (Canada) again and it seems that this issue has returned. I'm running the latest version of the integration, updated it this morning.  I tried requesting several different temperatures. The set temperature in homeassistant was the same as what I requested, just the actual set temp in the car (and what was shown in the bluelink app) was 2 degrees lower.
